### ISSUE TITLE
Separation of sent and received chats

### ISSUE THREAD

**Issue by majidit** [mattermost/mattermost-mobile#5335] opened 2021-04-17 06:00 UTC
Hello friends
Annoying enters

One of the things that can greatly increase the beauty and efficiency of the program
Separation of sent and received messages
Like WhatsApp and Telegram messengers where the sent messages are displayed on the right and the received messages are displayed on the left
And the username is displayed on the same side

**Comment by jasonblais** [comment] 2021-04-19 11:30
Thanks @majidit, closing this as a duplicate of https://github.com/mattermost/mattermost-server/issues/17432

**Closed by jasonblais** 2021-04-19 11:30 UTC
