### ISSUE TITLE
formatting errors between matterircd and mobile app [Edit: issue caused by incorrect rendering of MIRC color codes]

### ISSUE THREAD

**Issue by khronosschoty** [mattermost/mattermost-mobile#1501] opened 2018-03-13 21:49 UTC
#### Summary
Formatting of text from matterircd is not always correctly shown on the web interface or the mobile app etc. 

#### Steps to reproduce
Use the IRC bot Malibu developed by Stinger for the browser game utopia-game.com

#### Expected behavior
Formatting should be the same in the IRC client (or near the same).  

#### Observed behavior (that appears unintentional) 

![f95jrcd](https://user-images.githubusercontent.com/2358071/37367104-65e05dce-26fa-11e8-94c4-dd0639620ab2.png)

Numbers displayed that should not be displayed like the '7' in front of "Quadratic" 
or the "Runes: 12 4k" should just read "Runes: 4k" and it displays properly on the irc gateway just not in the mattermost webui. 

#### Possible fixes
Ignore MIRC color codes.

**Comment by koxen** [comment] 2018-03-14 14:48
are you claiming it looks correctly on mattermost-webapp?

**Comment by lindy65** [comment] 2018-04-18 08:24
Hi @khronosschoty, 

I'm going to close this issue off here for now as it seems the issue is with MIRC and not Mattermost.

**Comment by khronosschoty** [comment] 2018-04-18 15:04
Its not a MIRC issue, I don't even use MIRC and never really have. This is an issue with mattermost and matterircd. The issue is technically resolved, however, due to a fix by matterircd. Furthermore, I tried to make a feature request, because, I would love for mattermost to have support for MIRC colors. MIRC colors are a defacto standard that goes well beyond MIRC its self.

**Comment by lindy65** [comment] 2018-04-18 18:12
Thanks for clarifying @khronosschoty,

I've reopened this issue so you can link back to the feature request once you've created it on our [forum](https://mattermost.uservoice.com/forums/306457-general).  Others will also be able to up-vote your suggestion to increase its popularity.

Thanks!

**Comment by khronosschoty** [comment] 2018-05-09 14:25
will do ASAP (as in right now)

**Comment by khronosschoty** [comment] 2018-05-09 14:31
https://mattermost.uservoice.com/forums/306457-general/suggestions/34197916-add-support-for-mirc-color-codes-for-formatting-te

**Closed** 2018-05-10 23:52 UTC

**Comment by lindy65** [comment] 2018-05-11 06:49
Thank you @khronosschoty :)  Appreciated!
