### ISSUE TITLE
Adding prettier

### ISSUE THREAD

**Issue by FokinAleksandr** [mattermost/mattermost-mobile#7473] opened 2023-07-27 02:46 UTC
Hey folks. I think it's worth adding prettier for code formatting. What do you think?
https://prettier.io/

**Comment by enahum** [comment] 2023-07-27 02:48
Not really a fan + we already have a few linting rules that help with the formatting

**Comment by larkox** [comment] 2023-07-27 09:22
@FokinAleksandr What do you think it will bring to the project? What do you see in the code that prettier would make it "prettier"?

**Comment by FokinAleksandr** [comment] 2023-07-31 03:47
> @FokinAleksandr What do you think it will bring to the project? What do you see in the code that prettier would make it "prettier"?
For me personally the biggest benefit is that you don't have to think how to align your code at all. No need to spend time pressing tabs, spaces, enter. You just rapidly throw some code on 1 line, press the button and everything is aligned consistently with the rest of the project.
I do understand thought that this tool is pretty opinionated and formats code in a certain way without too many options to customize it.

**Comment by larkox** [comment] 2023-07-31 08:28
Right now that is made consistent with the linter rule. And it is fixed automatically using the `fix` command of the linter. Rarely it complains about some nested blocks and you have to fix it manually, but doesn't happen often. So that part of the issue is solved already, isn't it?

**Comment by FokinAleksandr** [comment] 2023-07-31 15:14
> Right now that is made consistent with the linter rule. And it is fixed automatically using the `fix` command of the linter. Rarely it complains about some nested blocks and you have to fix it manually, but doesn't happen often. So that part of the issue is solved already, isn't it?

Yeah but since it's not as strict you still have to spend time thinking how to format your code and spend time pressing tabs, enters, spaces and whatever. That's the main difference.

**Comment by larkox** [comment] 2023-07-31 15:34
Thank you for the explanation. I still think it is not needed, so I am tempted to close this ticket as a "won't do". Nevertheless, let's leave it for a week or two open, in case anyone else wants to chime in to try to convince. What do you think?

**Closed** 2024-01-04 18:33 UTC
