### ISSUE TITLE
App cannot connect to multiple servers

### ISSUE THREAD

**Issue by jnhssg** [mattermost/mattermost-mobile#2873] opened 2019-06-10 04:21 UTC
It would be a great feature if you could connect to multiple servers, because potentially multiple communities could switch to mattermost.

**Comment by amyblais** [comment] 2019-06-10 12:31
Hi @jnhssg, would you be open to upvoting this feature request: https://mattermost.uservoice.com/forums/306457-general/suggestions/10975938-ios-and-android-apps-should-allow-multiple-server?

I'll close this issue for now as a duplicate of the above feature request issue.

**Closed by amyblais** 2019-06-10 12:31 UTC
