### ISSUE TITLE
Mentioning users with numeric username.

### ISSUE THREAD

**Issue by VandorpeDavid** [mattermost/mattermost-mobile#4850] opened 2020-09-27 22:52 UTC
#### Summary

Numeric usernames are not being mentioned correctly in the mobile app.

#### Environment Information

- Device Name: Galaxy A50
- OS Version: Android 10, but reported by multiple users.
- Mattermost App Version: 1.35.1
- Mattermost Server Version: 5.24.0

#### Steps to reproduce

1. Enable Gitlab login.
2. Login through Gitlab with a user that has a numeric username.
2. Mention this user.

#### Expected behavior

The mention is highlighted, like it does in both the desktop app and browser (tested in Firefox).

![2020-09-27-233810_1920x1080_escrotum](https://user-images.githubusercontent.com/11561878/94377756-397ee500-0124-11eb-9df5-0d76ff8bcad6.png)

#### Observed behavior

The mention is not highlighted.

![image-943b1ca0-4cdb-4f9b-903c-360f7d69a4e6](https://user-images.githubusercontent.com/11561878/94377758-3a177b80-0124-11eb-85f4-220251fe0d13.jpg)

#### Possible fixes

I think the issue lies in this regex: https://github.com/mattermost/commonmark.js/blob/f6ab98dede6ce4b4e7adea140ac77249bfb2d6ce/lib/inlines.js#L879

I'm perfectly happy to create a PR if this is something you guys want fixed.

**Comment by enahum** [comment] 2020-09-27 22:55
Fyi @hmhealey @esethna @ashishbhate

**Comment by hmhealey** [comment] 2020-09-28 20:34
Interesting find. The reason it doesn't work is because we don't normally support usernames starting with a number, but OAuth lets you bypass that restriction. I'd welcome a PR to fix that, but I am slightly worried that there might be other side effects from having a numberic username such as other issues with not receiving mentions. I'll see if anyone has any idea of why we didn't allow them originally.

**Comment by ashishbhate** [comment] 2020-09-29 05:21
>but I am slightly worried that there might be other side effects from having a numberic username such as other issues with not receiving mentions.

Do you mean just on mobile? From the OP, numeric mentions work in the webapp and desktop. The web/desktop apps don't use commonmark (which was last updated a year ago). They use a different regex https://github.com/mattermost/mattermost-webapp/blob/master/utils/text_formatting.tsx#L24 which works with fully numeric mentions.

**Comment by hmhealey** [comment] 2020-09-30 21:16
I'm meaning there might be side effects on the server like mentions may not be triggered on the server similar to how they are on mobile.

I looked back and, as far as I can tell, we've never supported usernames starting with numbers, but I can't figure out why. I wonder if it might have been copied from team names not being able to start with numbers because the original version of Mattermost used subdomains for each team like `teamname.mymattermost.com`, and I don't think subdomains can start with numbers.

If they're handled correctly on the server, I think we could allow them everywhere, but we'll have to update that in the following places:
1) In any help text referring to the user's name needing to start with a letter
2) In this regex
3) In both apps when they try to verify valid usernames. The server actually doesn't do any validation on its own, so you can actually create a numeric username right now if you hit the API directly.

**Comment by amyblais** [comment] 2023-12-12 18:56
Closing some older issues. Please re-open this if the issue still reproduces on the latest version (v2.10),

**Closed by amyblais** 2023-12-12 18:56 UTC
