### ISSUE TITLE
Unable to login: password field must not be blank

### ISSUE THREAD

**Issue by stigok** [mattermost/mattermost-mobile#4146] opened 2020-04-13 10:06 UTC
#### Summary
I am unable to login with my username and password. It says I have a blank password field, which I don't.

#### Environment Information

- Device Name: Xperia Z3 Compact (Suzuran)
- OS Version: LineageOS 16.0, Android 9
- Mattermost App Version: 1.28.0
- Mattermost Server Version: 5.19.1 (DB 5.19.0)

#### Steps to reproduce
- Start app from scratch
- Provide mattermost URL
- Attempt to login with username and password

#### Expected behavior
- Get logged in successfully
**or**
- Get feedback for your invalid username or password

#### Observed behavior
- Receiving a message saying "Password field must not be blank"

![signal-attachment-2020-04-13-115547](https://user-images.githubusercontent.com/952936/79112437-dae4cb00-7d7e-11ea-9a4d-51883e4cbea0.png)

#### Possible fixes
Downgrading mobile app to 1.19 worked perfectly.

**Comment by amyblais** [comment] 2020-04-15 13:40
@stigok Do you see the same issue on v1.29?

**Comment by stigok** [comment] 2020-04-15 19:37
I will have to wait and see until v1.29 is available on F-Droid.

**Comment by licaon-kter** [comment] 2020-04-18 15:50
Yup, same here, even on 1.30.0 build via F-Droid (locally).

@amyblais Can anyone get the F-Droid version and test?

**Comment by stigok** [comment] 2020-04-21 12:56
Ping me if you want me to test a new version *available on F-Droid*.

**Comment by licaon-kter** [comment] 2020-04-27 20:44
Same for 1.30.1 build via F-Droid locally.

**Comment by licaon-kter** [comment] 2020-04-29 18:41
@stigok 1.30.0 is live: https://f-droid.org/en/packages/com.mattermost.rnbeta/

**Comment by robinmetral** [comment] 2020-04-29 19:14
> 1.30.0 is live: https://f-droid.org/en/packages/com.mattermost.rnbeta/

Just tested on my end, still getting the error :confused:

**Comment by licaon-kter** [comment] 2020-05-01 19:19
One _"strange trick that mattermost hates"_ is to install 5.19 and login, then upgrade to 5.28 and then to 5.30.

For some reason 5.19 to 5.30 asked me to login again, and of course failed.

**Comment by licaon-kter** [comment] 2020-05-02 21:27
1.30.1 is on F-Droid, as said ^^^ upgraded ok if already logged in. Still fails to login otherwise.

**Comment by licaon-kter** [comment] 2020-05-04 06:38
Hmm, looks like I can't send messages ...I get the red exclamation mark :(

**Comment by Roy-Orbison** [comment] 2020-05-08 03:16
To add weight, I'm getting this on Android 10 (not LineageOS).

Without looking into the code, it seems to be either a broken request, or an incompatibility with the server API. If I leave the password field blank and try logging in, the error is `Please enter your password`, but if I type anything at all and submit, the error becomes `Password field must not be blank`. It looks like the app's submitting something other than what the server expects.

**Comment by a3nm** [comment] 2020-05-08 09:23
Same problem here, "Mattermost Beta" version 1.30.1 from F-droid, server Mattermost Enterprise Edition version 5.21.0.

**Comment by sadamht** [comment] 2020-05-18 09:59
i have the same problem with this on Android. with Mattermost version 1.31.0
 please Mattermost Team Fix this issue

**Comment by licaon-kter** [comment] 2020-05-27 12:48
Same on 1.31.1 FYI

**Comment by robinmetral** [comment] 2020-05-27 16:25
@amyblais is this being addressed?

**Comment by amyblais** [comment] 2020-05-27 16:50
F-Droid is community maintained and is not officially supported by Mattermost. Has F-Droid been contacted about this issue?

**Comment by licaon-kter** [comment] 2020-05-27 16:57
F-Droid does not have the expertise, hence this issue and the request to _please take a look_.

Since you (Mattermost) are not interested (afaik) in maintaining a fully FOSS flavor of the app, the patches that the F-Droid contributors made up are all that we have.

And those, I guess, are rather old and broken, albeit it miraculously builds. :)

I keep updating the F-Droid metadata for new builds but I can't fix whatever that is broken.

**Comment by a3nm** [comment] 2020-05-27 17:01
I can confirm that the problem does not seem to be present on the APK of https://github.com/mattermost/mattermost-mobile/releases/tag/v1.31.1 so this bug may indeed be specific to F-droid.

However, if the F-droid folks are not managing to build the application in a way that works, so that the only way to get a working copy of the app is via the binary builds on Google Play, the App Store, and the binary releases on Github, then there's a question of whether this software indeed qualifies as free software...

**Comment by Adrian-Hufnagl** [comment] 2020-06-02 13:50
Im getting the same error by starting the App from scratch
Tested Version 1.19, 1.28, 1.30. Android Versions 6, 8, 10
It does not seem to be related just to the F-Droid Team

**Comment by enahum** [comment] 2020-06-02 13:53
Are you building the app yourselves? Are you applying the patch for `rn-fetch-blob`? Without the patch being applied this is exactly what happens...

**Comment by Adrian-Hufnagl** [comment] 2020-06-03 12:05
I have now ran it succesfully on android. I set the project up again with MacOS.
I took the Repo from Mattermost-Mobile. My other failed attempts ran with rn-fetch-blob 0.12.0

**Comment by enahum** [comment] 2020-06-03 12:12
Now I wonder if the other patches are also being left out...

**Comment by licaon-kter** [comment] 2020-06-03 18:33
@enahum Where are the patches applied exactly? I've looked at https://developers.mattermost.com/contribute/mobile/build-your-own/ or https://github.com/mattermost/mattermost-mobile/blob/master/Makefile and I can't grasp what step should do that.

**Comment by enahum** [comment] 2020-06-03 19:21
@licaon-kter https://github.com/mattermost/mattermost-mobile/blob/master/Makefile#L74 which is triggered by https://github.com/mattermost/mattermost-mobile/blob/master/package.json#L158 and applies all the patches here https://github.com/mattermost/mattermost-mobile/tree/master/patches

**Comment by licaon-kter** [comment] 2020-06-04 15:50
The main buildserver log is rather spartan so I've run it locally, for 296 
[com.mattermost.rnbeta_296.log.gz](https://github.com/mattermost/mattermost-mobile/files/4730552/com.mattermost.rnbeta_296.log.gz)

The interesting bits start at line 1687, I guess:
```
patch-package 6.2.1
Applying patches...
react-native@0.61.5 ✔
react-native-fast-image@8.1.5 ✔
react-native-haptic-feedback@1.9.0 ✔
react-native-image-picker@2.3.1 ✔
react-native-keyboard-tracking-view@5.6.1 ✔
react-native-local-auth@1.6.0 ✔
react-native-mmkv-storage@0.3.1 ✔
react-native-navigation@6.3.0 ✔
react-native-notifications@2.0.6 ✔
react-native-passcode-status@1.1.2 ✔
react-native-vector-icons@6.6.0 ✔
Error: Patch file found for package react-native-youtube which is not present at node_modules/react-native-youtube
```

But the files are there:
```
vagrant@basebox-stretch64:~/build/com.mattermost.rnbeta/patches$ ls -la
total 404
drwxr-xr-x  2 vagrant vagrant   4096 Jun  4 13:31 .
drwxr-xr-x 18 vagrant vagrant   4096 Jun  4 13:41 ..
-rw-r--r--  1 vagrant vagrant  14209 Jun  4 13:31 react-native+0.61.5.patch
-rw-r--r--  1 vagrant vagrant   2558 Jun  4 13:31 react-native-fast-image+8.1.5.patch
-rw-r--r--  1 vagrant vagrant    832 Jun  4 13:31 react-native-haptic-feedback+1.9.0.patch
-rw-r--r--  1 vagrant vagrant  14579 Jun  4 13:31 react-native-image-picker+2.3.1.patch
-rw-r--r--  1 vagrant vagrant  19884 Jun  4 13:31 react-native-keyboard-tracking-view+5.6.1.patch
-rw-r--r--  1 vagrant vagrant   7101 Jun  4 13:31 react-native-local-auth+1.6.0.patch
-rw-r--r--  1 vagrant vagrant   2521 Jun  4 13:31 react-native-mmkv-storage+0.3.1.patch
-rw-r--r--  1 vagrant vagrant   4306 Jun  4 13:31 react-native-navigation+6.3.0.patch
-rw-r--r--  1 vagrant vagrant  21395 Jun  4 13:31 react-native-notifications+2.0.6.patch
-rw-r--r--  1 vagrant vagrant   1399 Jun  4 13:31 react-native-passcode-status+1.1.2.patch
-rw-r--r--  1 vagrant vagrant   1549 Jun  4 13:31 react-native-vector-icons+6.6.0.patch
-rw-r--r--  1 vagrant vagrant   3911 Jun  4 13:31 react-native-youtube+2.0.0.patch
-rw-r--r--  1 vagrant vagrant    591 Jun  4 13:31 redux-persist+6.0.0.patch
-rw-r--r--  1 vagrant vagrant 278798 Jun  4 13:31 rn-fetch-blob+0.12.0.patch
```
...right so, the files are parsed in order and `patch-package` bails out on the first error, so we need to remove the now useless patch to allow it to apply all the other patches.

I was expecting the whole build to fail if the patching fails or _(like the actual `patch` does)_ the patching to continue with the rest of the files, the current behaviour is inconsistent in your build system, imho.

Ref: Superseded by https://github.com/ds300/patch-package/pull/217 when merged maybe

**Comment by dromer** [comment] 2020-06-06 17:17
Server: `5.23.1`
With client `1.19.0` this worked fine.

After upgrading to `1.31.1` I was able to reuse the login token. It was not possible to see old channel messages or send messages, but I could see new messages coming in.
After logging out I get the same `password must not be blank` message and am unable to use the app.

This seems to me like an issue in how the client communicates to the server and goes deeper than just the login screen.

**Comment by Roy-Orbison** [comment] 2020-06-11 00:36
I can confirm I'm able to log in, view all previous messages, etc. with v1.31.2. 🎉 🍾

**Comment by dromer** [comment] 2020-06-11 06:11
Yup, with latest version of the app in f-droid `1.31.2` things seem to work.

**Comment by a3nm** [comment] 2020-06-11 06:47
Same here. Thanks for fixing this issue! I think the bug can be closed.

**Comment by sadamht** [comment] 2020-06-11 11:33
Same here

**Closed** 2020-06-28 11:58 UTC

**Comment by roya002ar** [comment] 2024-09-26 22:34
Agent_Liza_BDT

**Comment by roya002ar** [comment] 2024-09-26 22:35
![Uploading Screenshot_2024-09-27-04-35-02-83_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

**Comment by roya002ar** [comment] 2024-09-26 22:37
### [`__`](url
![Uploading Screenshot_2024-09-27-04-35-02-83_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()
)

**Comment by roya002ar** [comment] 2024-09-26 22:37
https://birpay-gate.com/login

**Comment by roya002ar** [comment] 2024-09-26 22:38
https://birpay-gate.com/login
![Uploading Screenshot_2024-09-27-04-35-02-83_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()
