### ISSUE TITLE
aws-partition not found 

### ISSUE THREAD

**Issue by cibinstark123** [mattermost/mattermost-mobile#4428] opened 2020-06-17 05:50 UTC
when im using the command (make build-android) it gives me a error like aws-partition not found..can anyone know about this?any help ?

**Comment by enahum** [comment] 2020-06-17 14:02
Hi @cibinstark123 you need to install fastlane.. 
change directory to the fastlane folder, run `bundle install` and it should be good to go as long as you  have all the requirements.

more info here https://developers.mattermost.com/contribute/mobile/build-your-own/

**Comment by enahum** [comment] 2020-06-28 11:55
@cibinstark123 Were you able to run this? Can we close the issue?

**Comment by jasonblais** [comment] 2021-08-21 18:34
We haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Closed by jasonblais** 2021-08-21 18:34 UTC
