### ISSUE TITLE
Build gets stuck at bundleReleaseJsAndAssets

### ISSUE THREAD

**Issue by Rudloff** [mattermost/mattermost-mobile#1671] opened 2018-05-11 16:55 UTC
#### Summary
`gradle assembleRelease` often gets stuck at `bundleReleaseJsAndAssets`.

#### Environment Information
I'm building on Debian 9.4.

#### Steps to reproduce
```bash
cd android/
./gradlew assembleRelease
```

#### Expected behavior
The build completes.

#### Observed behavior
When I try to build 1.8.0, 90 % of the time, the build gets stuck at `bundleReleaseJsAndAssets`.
I tried to let it run for 30 minutes and it never stops. By looking at `ps aux`, I think `react-native bundle` finishes correctly but Gradle does not notice it for some reason.

#### Possible fixes
I found a workaround that works [here](https://github.com/facebook/react-native/issues/11696#issuecomment-270428347).

**Comment by enahum** [comment] 2018-05-15 12:42
Hi @Rudloff 

As you pointed out in your workaround (btw thanks for taking the time to find it) this seems to happen only in some OS's (actually this is the first time I ever seen this) and is not actually caused by our app directly but a third party which we depend on meaning that we cannot do much to fix it, but we could add it in our troubleshooting section in our docs.

Thanks again from bringing this to our attention.

**Comment by amyblais** [comment] 2018-05-16 22:35
The doc PR is now merged so I will close this issue for now.

**Closed by amyblais** 2018-05-16 22:35 UTC

**Comment by nicksanchezc137** [comment] 2020-02-13 06:40
Try Building using gradlew assembleRelease -x bundleReleaseJsAndAssets
