### ISSUE TITLE
Android client shortens names too early (OnePlus 6)

### ISSUE THREAD

**Issue by ibot3** [mattermost/mattermost-mobile#2009] opened 2018-08-15 17:41 UTC
#### Summary
The Layout was fine on my OnePlus 5, but on my OnePlus 6 (bigger display), the mattermost app shortens channel and usernames that are already short enough.

#### Environment Information

- Device Name: OnePlus 6
- OS Version: Android 8.1.0
- Mattermost App Version: 1.10.0 (Build 127)
- Mattermost Server Version: 5.1.0

#### Steps to reproduce
Use App on OnePlus6

#### Expected behavior
Print full names

#### Observed behavior
Names get shorten too early. Examples:
- "BuS" to "B..."
- "matterbridge" to "matter-"
- "abcdef" to "ab-"

You may also notice the time floating around somewhere in the middle.

![screenshot_20180815-192917__01](https://user-images.githubusercontent.com/8113443/44163136-d310e700-a0c2-11e8-9eb2-a993605e86b7.jpg)

**Comment by amyblais** [comment] 2018-08-15 18:26
Hi @ibot3! Thank you for reporting this - we're releasing v1.11 tomorrow and I'm wondering if you'd like to test this out with the newest release in case it includes a fix for this issue?

**Comment by amyblais** [comment] 2018-08-23 18:43
@ibot3 Sorry about that! I've asked our QAs to help test this out.

**Comment by amyblais** [comment] 2018-08-23 22:56
Hi @ibot3,

Our QAs are not able to reproduce this - are other screens in the app showing the same issue (e.g. other than the channel view screen)?

**Comment by ibot3** [comment] 2018-08-24 09:47
No, it only happens when viewing a channel.

**Comment by amyblais** [comment] 2018-08-24 13:30
Hi @ibot3, this seems to be an issue on the RN side - you can follow it here: https://github.com/facebook/react-native/issues/15114.

**Comment by amyblais** [comment] 2018-08-27 13:14
Hi @ibot3,

We created a ticket for this here: https://mattermost.atlassian.net/browse/MM-11845. 

Our devs are taking a look if they are able to fix it - however, since we're not able to reproduce the issue, we're not able to effectively test if the fix works. Hence, we're wondering if you'd be able to help with testing and/or fixing of the issue? We're able to send you an apk file and give guidance on how you can help if you're interested.

**Comment by ibot3** [comment] 2018-08-29 10:45
Yes, I am interested.

**Comment by amyblais** [comment] 2018-08-29 13:09
Awesome! Do you have an idea on how to get started if you have a chance to help with a fix?

Our devs will also investigate a fix for this, but it might not make it to v1.12 as we haven't been able to reproduce this internally yet.

**Closed** 2018-10-11 14:03 UTC
