### ISSUE TITLE
IOS app fails to send message, ajax spinner ad infinitum

### ISSUE THREAD

**Issue by fmp777** [mattermost/mattermost-mobile#724] opened 2017-07-06 13:59 UTC
#### Summary
Very frequently, ios app fails to send message, just endless ajax spinner.  Must reboot app to reconnect.

#### Environment Information

- Device Name: iPhone 6 Plus
- OS Version: 10.3.2 (latest)
- Mattermost App Version: 3.5
- Mattermost Server Version: 3.10.0 Enterprise

#### Steps to reproduce
I cannot determine how to reproduce, it happens frequently and randomly across all staff iphones (have not tested android).  Does NOT happen with desktop client nor web client.   Perhaps happens when you switch wifi access points, or go from wifi to 3g with app open and active.

#### Expected behavior
Well, uhm, message sends.

#### Observed behavior
The ajax spinner that shows whenever you send a message, it never goes away.  You can send message after message to any channel or person and they all just spin.  Must reboot app and retype every message.

#### Possible fixes
I'm guessing you are using websockets (never looked at the code) and on a network switch are not always successfully reconnecting the websocket.

**Comment by lfbrock** [comment] 2017-07-13 13:31
Hi @fmp777 - would you be able to try with the [new app from here](https://about.mattermost.com/mattermost-android-app/) to see if the issue still reproduces?

**Comment by fmp777** [comment] 2017-07-13 16:47
Well, I dont run Android.  And for IOS, I found the new native app and excitedly deleted the "classic" one.  This issue might very well also be more related to the web-app since this app is just little more than repackaging the webapp, but I never experience it on the web-app because when you use the webapp you are stationary and not switching networks, which is where I believe the problem lies.

**Comment by lfbrock** [comment] 2017-07-13 23:05
@fmp777 - ah sorry, meant to link to the iOS one but glad you found it. 

I'm going to close this issue since it seems fixed with the new apps, and will check if connection issues or something could cause it to happen on the webapp.

**Closed by lfbrock** 2017-07-13 23:05 UTC
