### ISSUE TITLE
Blurry or fuzzy font display in Android app

### ISSUE THREAD

**Issue by randallgrout** [mattermost/mattermost-mobile#2476] opened 2018-12-24 02:13 UTC
#### Summary
As of version at least 1.15.1, the Android app's fonts are shown with a slight blur appearance.

#### Environment Information

- Device Name: OnePlus 6
- OS Version: Android 9.0
- Mattermost App Version: 1.15.1 (build 166)
- Mattermost Server Version: 5.4.0

#### Steps to reproduce
View app with version 1.15.1.  Compare to version 1.14.0 (build 158).

#### Expected behavior
Sharp and crisp text as previously seen.

#### Observed behavior
See the screenshots, two screens from each app version.

v1.14.0
![screenshot_20181223-201649__01](https://user-images.githubusercontent.com/22521672/50389345-36f18f00-06f7-11e9-8c04-98205e0e615d.jpg)
![screenshot_20181223-201640](https://user-images.githubusercontent.com/22521672/50389348-407af700-06f7-11e9-82a4-fb4c73f9e130.jpg)

v1.15.1
![screenshot_20181223-200903__01](https://user-images.githubusercontent.com/22521672/50389339-23462880-06f7-11e9-885c-f5bb6ea7da8f.jpg)
![screenshot_20181223-200818](https://user-images.githubusercontent.com/22521672/50389342-293c0980-06f7-11e9-97e9-a0d5a8cb666a.jpg)

#### Possible fixes
Maybe this is related at https://github.com/facebook/react-native/issues/21507?  (Fixed in react-native v0.57.8).  They mention a workaround, but then fixed the bug with an update.

**Comment by jasonblais** [comment] 2018-12-29 15:05
Thanks for the report @randallgrout! I checked and the issue is fixed with react-native v0.57.8 as you said - we'll likely update to that version (from v0.57.5) on our next dependency update after holidays.

**Closed** 2019-06-21 15:24 UTC
