### ISSUE TITLE
iOS Mattermost app shows frequent crashes

### ISSUE THREAD

**Issue by danieldres** [mattermost/mattermost-mobile#4564] opened 2020-07-13 15:40 UTC
#### Summary
The Mattermost app on iOS crashes frequently, especially when looking at threads with posted images, but also when e.g. just copying the app version info and server version info from my phone to the computer.

#### Environment Information

- Device Name: iPhone 6s
- OS Version: iOS 13.5.1
- Mattermost App Version: 1.32.2 (Build 370) 
- Mattermost Server Version: 5.23.0 (Build 5.23.1)

#### Steps to reproduce
Use an iPhone 6s with up to date iOS and up to date Mattermost. My colleague has the same phone and the same problems. 

#### Expected behavior
The app should work without crashes.

#### Observed behavior
The app crashes, usually after a few seconds of correct behaviour. I am able to post material to Mattermost from Pictures, by sharing it via Mattermost and adding some text. Any other posting on Mattermost (even just posting a few words of text material) from the phone is defeated by the very quick crash of the app. No error message when crashing.
I used to have the same problem with an earlier version and could fix it by disabling the zoom feature for my iPhone. Now this feature is off, but the bug came back.

#### Possible fixes
Something the phone does after just a few seconds?? Really, no idea.

**Comment by josephbaylon** [comment] 2020-07-13 17:05
I tested on the following specs,
Device Name: iPhone 6s
OS Version: iOS 13.5.1 and 12.4
Mattermost App Version: 1.32.2
Mattermost Server Version: 5.23.0 and 5.24.2

I also tested on iPhone X 13.5.1.

Unfortunately I'm not able to reproduce the issue in the following areas,
1. post image and text in main thread
2. post image and text in reply thread
3. post image and text via share extension

@danieldres Is it possible for you to test on a different device to narrow if it's an iPhone 6s issue?

**Comment by danieldres** [comment] 2020-07-14 07:28
Thanks @josephbaylon for the quick reply. I repeated the test with my colleague's phone:
* iPhone XR
* iOS 13.5.1
* Mattermost app version 1.32.2

In my colleague's case, it is even worse. The app won't even start, he has a blank white screen.

Also, I repeated the test on my phone. Crash after just a few seconds, even when not doing anything. The "Mattermost classic" app works fine, but it doesn't allow me to post anything, so I really need the regular "Mattermost" app.

Our institute's server has the following specs:
Mattermost Team Edition
Mattermost Version: 5.23.1
Database Schema Version: 5.23.0
Database: postgres

Build Date: Tue Jun 2 02:09:52 UTC 2020

**Comment by amyblais** [comment] 2020-07-14 14:57
@danieldres Can you test by using the same phone but connecting to a different server (e.g. https://community.mattermost.com)? If you can still reproduce, please provide step-by-step repro steps.

There could be a specific image causing an out of memory crash.

**Comment by danieldres** [comment] 2020-07-16 15:38
Hi @amyblais, now I tested two different things. First, I connected too community.mattermost.com. No crash.
Second, I used our institute's usual server, but selected channels with low traffic. No crash.
The crashes occur in two channels that have a lot of images, I count 99 cellphone pictures in one of the two channels (each one typically 1-2 MB, so the channel has maybe 100-200 MB). The other channel is probably similar.
Now I have created a private channel on our institute's server and try to fill it up with images... so far it has not crashed, whereas for the two channels I need for my work I see reproducibly crashes after them being open for just a few seconds.

**Comment by danieldres** [comment] 2020-07-16 15:43
OK update: Now the test channel I created has 65 photos (~1 MB each), one PDF. When I try to add one photo by using the "take picture" function on my phone, it crashes after I took the picture, but before I am able to click "use photo". Reproducible. When I post text from my phone, no crash.

**Comment by danieldres** [comment] 2020-07-16 15:49
Second update: I created yet another private test channel. In the brand new channel, I am able to post a photo using the "use photo" function. So one problem seems to be something for already large channels when you try to add a photo. 

The second problem, more serious, is for the channels I use for my work. Those crash even when I don't do anything. I see the same behaviour now in the private Test channel, where I have now accumulated 100 images and a couple of PDF documents. This test channel also crashes on my phone even when I don't do anything.

**Comment by amyblais** [comment] 2020-07-16 17:08
@josephbaylon Can you help reproduce? Sounds that the issue is when channels have a large amount of photos / files, the app crashes either when just switching to the channel or when trying to add another photo in the channel.

@danieldres Do you see the same issue with v1.33.1?

**Comment by josephbaylon** [comment] 2020-07-16 18:54
@amyblais @danieldres Unfortunately, I'm still not able to repro the issue on a channel with lots of images and file attachments. I tested both v1.32.2 and v1.33.1

@danieldres If the channel you created is on Community server, can you please add my user to the channel `joseph.baylon` and I'll test there and try to see if I can reproduce. Thanks.

**Comment by danieldres** [comment] 2020-07-20 12:57
@amyblais @josephbaylon now I created a channel on the community server that reliably crashes. I just checked, on my phone we have v1.33.1. The iOS is 13.5.1. I added both of you to my test channel so you can see whether you can reproduce the problem.

**Comment by danieldres** [comment] 2020-07-20 12:59
Ok sorry @amyblais, you seem to have a different user ID on the community server. The channel is here:
https://community.mattermost.com/core/channels/iphone-crash-test
I can add you if you tell me your ID there.

**Comment by josephbaylon** [comment] 2020-07-20 17:35
@danieldres @amyblais Yes, I'm able to repro the issue using the channel you created. I'm on v1.33.1 for iOS 13.5.1 
It doesn't look like a recent regression.
It looks like an issue that only occurs when channel tries to load tons of images and attachments

**Comment by amyblais** [comment] 2020-07-20 17:43
Thanks, opened a ticket: https://mattermost.atlassian.net/browse/MM-27139.

**Comment by yewkay** [comment] 2020-09-04 03:22
I am in charge of deploying MM in my company and for the past few months have the same issue with iPhones in the company as well. The ticket is marked as closed by my colleagues are still having the issue. We have a channel where our colleague posts job updates as images and only that channel crashes. It still does now.

**Comment by larkox** [comment] 2023-01-10 17:41
@yewkay are you still experiencing this? If so, can you try with the new V2 app?

**Closed** 2023-12-06 21:50 UTC
