### ISSUE TITLE
Single SignON  - Error: disallowed_useragent

### ISSUE THREAD

**Issue by byvinx** [mattermost/mattermost-mobile#975] opened 2017-10-02 12:14 UTC
#### Summary
403

Error: disallowed_useragent

this user agent is not allowed to make an oauth authorization request to google

#### Environment Information

- Device Name:  Huawey p9 Light
- OS Version: Android 7.0
- Mattermost App Version:  1.2.0
- Mattermost Server Version: 4.2.0

#### Steps to reproduce
Hi, I have mattermost configured for "only" access via a gitlab account and Gitlab that allows access "only" through a google account.
From web browser everything works well. 
When I try to get in from the app the problem is that Google does not accept authorization oauth requests, I have a error response:

403
Error: disallowed_useragent
This user agent is not allowed to make an OAuth authorization request to Google as it is classified as an embedded user-agent (also known as web-view). Per our policy, only browser are permitted to make authorization request to Google.

#### Expected behavior
Login successfully

#### Observed behavior
Login with googlea account failed

**Comment by enahum** [comment] 2017-10-02 15:17
looks like a duplicate of #622

**Closed** 2017-10-25 15:40 UTC
