### ISSUE TITLE
Can't send message with smiles on iOS in case I use Gboard keyboard

### ISSUE THREAD

**Issue by acostroma** [mattermost/mattermost-mobile#3675] opened 2019-12-09 11:58 UTC
#### Summary
Can't send message on iOS

#### Environment Information

- Device Name: iPhone 6, iPhone SE
- OS Version: iOS 12.4.3, latest iOS 13
- Mattermost App Version: 1.25.1 (Build 247), 1.26.0 (Build 249)
- Mattermost Server Version: 5.16.0 (Build 5.16.3)

#### Steps to reproduce
1 Try to send message
2 Always get 'Unable to send your message'
(sometimes I can send 1 message, but I can never send more)
3 Tap 'Try Again' numerous times => No luck

**Comment by enahum** [comment] 2019-12-09 12:24
@acostroma have you verified your internet connection? is the server reachable? this looks like a connectivity issue more than anything else.

**Comment by acostroma** [comment] 2019-12-09 12:31
@enahum it's ok with internet connection.
I receive messages with no problems.
This issue reproduces on WiFi & cellular data.

**Comment by enahum** [comment] 2019-12-09 12:32
@acostroma does it reproduces to anyone else on your team? are there any logs on the server ?

**Comment by acostroma** [comment] 2019-12-12 07:14
The issue reproduces on the latest beta (1.26.0 b249) :(

**Comment by enahum** [comment] 2019-12-12 11:21
@acostroma my friend I think you’ll need to provide much more detail in order for us to try and get to the root cause. As you would understand your issue is about the core functionality of the product and would’ve become a red flag for the app and wouldn’t ship.

Please try and provide as much detail as you can including server deployment etc...

**Comment by acostroma** [comment] 2019-12-12 11:29
@enahum maybe you have an article describing the best way to gather as much information as possible?

**Comment by svelle** [comment] 2019-12-12 12:07
@acostroma there's not really a guide but you can go through these questions: https://docs.mattermost.com/process/support.html#general-questions-for-any-issues

Any additional infrastructure info is also relevant. Like if you have a proxy like nginx in front of mattermost and the configuration files of those.

Please don't post the info here. You can send them directly to me on the mattermost community server (https://community.mattermost.com, my name there is `@sven.huester`) or you can send the info to support@mattermost.com and note this ticket in the email.

Also infos like how many users are on this deployment and the size/configuration of the server (how many CPU-cores, RAM, etc.).

Let me know if you need any more info.

**Comment by acostroma** [comment] 2020-01-21 14:51
@enahum @svelle I found out that issue reproduces **only** if I use smiles. Ordinary text messages work perfect!

**Comment by acostroma** [comment] 2020-01-28 08:19
@enahum @svelle Does anyone interested in fixing that bug?
I can **always** reproduce it!

**Comment by enahum** [comment] 2020-01-28 11:53
@acostroma can you please provide exact repro steps, as you can **always** reproduce. Without does exact repro steps it is a bit difficult to figure it out as no one else has reported it either.

**Comment by acostroma** [comment] 2020-01-28 12:02
@enahum 
1 open latest Mattermost on iphone
2 write message to anyone with the following content:
"test :tada:" 
Result: message send failed. You can tap "Retry" infinite amount of time it will **never** send it

At the same, if I try to send the message containing only "test" everything works perfectly.

Should I record a video for you?

**Comment by acostroma** [comment] 2020-01-28 12:07
@enahum @svelle I got an update on this. This happens only if I insert smile using google's keyboard "Gboard"
In case I insert smile manually letter by letter everything works.

**Comment by enahum** [comment] 2020-01-28 12:10
@acostroma Ok “gboard” is actually an important piece of the puzzle.

@josephbaylon would you be willing and try an repro? And maybe with SwiftKey as well?

Thanks

**Comment by svelle** [comment] 2020-01-29 09:48
@enahum @acostroma I tried reproing (see attached video) but it worked. Anything I missed?


[RPReplay_Final1580291145.zip](https://github.com/mattermost/mattermost-mobile/files/4127244/RPReplay_Final1580291145.zip)

**Comment by acostroma** [comment] 2020-01-29 10:55
@svelle @enahum Did you try it on iPhone? It looks like you have used Android...
Here is my video
https://www.dropbox.com/s/o845ogr88zryzg0/VID_20200129_133915.mp4?dl=0

**Comment by acostroma** [comment] 2020-01-31 10:40
@svelle @enahum were you able to reproduce it locally?

**Comment by svelle** [comment] 2020-01-31 10:44
@acostroma the video was recorded on an iPhone XR, so unfortunately no :/

**Comment by jasonblais** [comment] 2021-08-03 14:44
@josephbaylon would you be open to try reproduce this issue on iPhone?

@svelle anything particular they should be looking for from the server logs?

**Comment by larkox** [comment] 2022-07-28 14:06
Closing this due to its age. @acostroma If this is still an issue for you, would be great if you can test with the new V2 version (https://mattermost.com/blog/mobile-beta-program-v2/ ) and reopen the ticket if needed.

**Closed by larkox** 2022-07-28 14:06 UTC
