### ISSUE TITLE
Chat/Room slider does not fully open/close sometimes

### ISSUE THREAD

**Issue by Centzilius** [mattermost/mattermost-mobile#2897] opened 2019-06-19 12:50 UTC
#### Summary
Sometimes the Chat list slider does not fully open/close.

#### Environment Information

- Device Name: Oneplus 6T
- OS Version: Android 9
- Mattermost App Version: 1.20.0 (Build 198)
- Mattermost Server Version: 5.4.0 EE w/o License

#### Steps to reproduce
It's kind of tricky but it happens sometimes on day to day usage. Please see the video attached.
https://youtu.be/vEemTlhZ-aA

#### Expected behavior
Open/Close completely.

#### Observed behavior
Please see the video.
https://youtu.be/vEemTlhZ-aA

**Comment by amyblais** [comment] 2019-06-19 18:30
Hi @Centzilius, this might be similar to https://github.com/mattermost/mattermost-mobile/issues/2826 which we haven't been able to reproduce so far internally.

Would you be open to testing this on a recent server version (such as v5.11 or v5.12)? Do you see any errors in "Report a Problem"?

**Comment by Centzilius** [comment] 2019-06-21 13:47
Hi @amyblais,
In contrast to #2826 I do not have to force close the app for it to become unstuck.
Regarding the server version I've updated the Martermost Server to 5.12 (I think yesterday) and still experience this issue although I'll try later today to reproduce it on pre-release.mattermost.com. The "Report a Problem" button did not indicate an error related to this (only to a different issue).

**Comment by skhrshin** [comment] 2019-09-02 03:26
It happens on my environment too.

- Device Name: ZenFone4 Max Pro
- OS Version: Android 7.1.1
- Mattermost App Version: 1.22.1 (Build 225)
- Mattermost Server Version: 5.13.0 (Build 5.13.2)

I often see this behavior when I flick the screen from left edge to right rapidly.

**Comment by cheald** [comment] 2020-02-24 17:17
This happens more often than not when I try to slide the drawer out using touch gestures. A quick flick (like I'd use with slack) results on the drawer opening only far enough to cover the avatar column. I have to use the hamburger menu to collapse it afterwards. I have to use a very slow gesture to get the drawer to come all the way out. It's maddening.

It feels like an element in the UI stream is capturing input (usually the chat stream scrolls a bit; I did manage to get a post menu to open once) it might be that and preempting the slide.

It's definitely a race condition, because if I grab the slider and don't trigger the bug immediately, I can swipe all over with the slider held and it just goes back and forth as expected.

I'm using a pixel 3 xl, latest Android release and patch, app build 268, server build 5.16.3.

**Comment by amyblais** [comment] 2020-02-25 23:16
Hi all, we have made some changes to upcoming v1.29 release where the side bar on Android will use sideMenu from the navigation library, which will improve this behaviour.

**Comment by cheald** [comment] 2020-02-26 14:11
My mobile client shows 1.29.0 (build 271) already. What build or version string should I expect to see with the new behavior?

**Comment by svelle** [comment] 2020-02-26 14:57
@cheald 1.29.0 is supposed to fix the sidebar getting stuck issue. I've also tested this on some devices as well as my personal pixel 3 and couldn't repro anymore. The issue posted by @Centzilius was fixed as far as I'm concerned. 
I'd like to get some more info on the other problems mentioned.
Would you mind if we move that conversation to a different issue to prevent confusion between the two topics? I can open it if you want to.

**Comment by cheald** [comment] 2020-02-26 14:58
Sure! Sorry for wandering off topic!

**Comment by svelle** [comment] 2020-02-26 15:46
> Sure! Sorry for wandering off topic!

No worries, just want to make sure we're able to follow all issues the best we can :)

**Comment by enahum** [comment] 2020-08-29 10:56
Going to close this issue as it hasn’t had any recent activity

**Closed by enahum** 2020-08-29 10:56 UTC
