### ISSUE TITLE
Unable to switch servers on iOS App

### ISSUE THREAD

**Issue by flyingpolcat** [mattermost/mattermost-mobile#7791] opened 2024-01-27 14:32 UTC
#### Summary
Bug report in one concise sentence

### Environment Information
  - Device Name: iPhone 14 Pro
  - OS Version: 17.3
  - Mattermost App Version: 2.12.0 (Build 499)
  - Mattermost Server Version: 9.3.0 (Build 7014621505)

#### Steps to reproduce
Issue is unable to reproduce on all mobile devices and appears to be random. Despite multiple app re-installs, the behavior is consistent on this device.

#### Expected behavior
After the recent app update for iOS, I am unable to switch servers using the 'Your servers' icon in the upper left. Futhermore, the channel name on the top of the screen is cut off. This "shift" up hides the the "servers" icon and part of the channel name behind the classification banner at the top of the screen.

#### Observed behavior (that appears unintentional)
The attached photo was intentionally cropped and classification banner edited. But as you can see, the "Your servers" icon is missing when it should be located just below the classification banner.

![IMG_6508](https://github.com/mattermost/mattermost-mobile/assets/157898001/e8c08749-6329-49ac-bdf6-bf62dd736115)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by flyingpolcat** [comment] 2024-01-27 14:50
I am by no means an app developed, just an end user trying to report an issue I and at least two others in my squadron are experiencing.

**Comment by enahum** [comment] 2024-01-27 23:23
Closing as a duplicate of #7764

**Closed** 2024-01-27 23:24 UTC
