### ISSUE TITLE
iOS: Images I've uploaded disppear after couple of weeks

### ISSUE THREAD

**Issue by madhermit** [mattermost/mattermost-mobile#4547] opened 2020-07-07 17:11 UTC
#### Summary
Images that I've uploaded will disappear from my Mattermost channel history after a time, resulting in a broken link icon. 

#### Environment Information

- Device Name: iPhone 8+
- OS Version: iOS 12.3.2
- Mattermost App Version: v1.32.2
- Mattermost Server Version: 5.21.0

#### Steps to reproduce
1.) Upload a photo from local phone image library to Mattermost using the image icon below the text entry box.
2.) Wait a couple of weeks
3.) See only the images that you've uploaded disappear and be replaced with a broken link icon

#### Expected behavior
I expect the images to remain visible indefinitely.

#### Observed behavior
None of the other users of the channel are experiencing this issue with their own images, and also continue to see the images I uploaded. If I uninstall the app and reinstall the images appear once again.

Thanks in advance!

**Comment by amyblais** [comment] 2020-07-08 13:42
@madhermit 
1. Do you see any errors on your app's Report a Problem page?
2. Do you see any server log errors?
3. Would you have a screenshot to illustrate what you're seeing?
4. Is this happening also on browser / webapp?

**Comment by madhermit** [comment] 2020-07-08 22:42
Hi @amyblais 
1.) No errors on the Report a Problem page, clicking it just opens Apple Mail
2.) No server log errors; additionally, after querying other users of this team, no one else seems to have this problem
3.) See attached
4.) This is not happening on the webapp, the images are still there on the webapp, yet missing from the mobile app.


![IMG_9723](https://user-images.githubusercontent.com/1425712/86977278-1fd78e00-c131-11ea-97bb-675c65e83d3c.PNG)

Thanks!

**Comment by ahmaddanialmohd** [comment] 2020-07-13 23:40
Hi, @madhermit 

From the channel that contains the broken image, may I know if you are able to tap and hold on the icon and obtain the link to this image like this?

![image](https://user-images.githubusercontent.com/49461314/87363902-c9d96f00-c5a4-11ea-95fe-e63bd888ec51.png)

If yes, can you paste the URL copied on to your mobile web browser and open it to confirm that it is showing the right image?

Just trying to understand if this image is specifically broken on the iOS app, especially since it is only affecting you. 

> If I uninstall the app and reinstall the images appear once again.

Based on the statement above, does that mean that the broken images will reappear again but it will affect new uploaded images or will it just cause the old images to be broken again after a few weeks?

Also, which network (mobile service provider / WiFi / VPN / proxy) were you connected to when you reproduce the issue? If your Mattermost instance is publicly hosted, can you please confirm that you are able to connect to the mobile service provider and reproduce the problem too?

**Comment by madhermit** [comment] 2020-07-15 00:59
@ahmaddanialmohd

> If yes, can you paste the URL copied on to your mobile web browser and open it to confirm that it is showing the right image?

When the icon is pressed I do get that pop-up screen and copying the link into the mobile browser does bring up the expected image.

> Based on the statement above, does that mean that the broken images will reappear again but it will affect new uploaded images or will it just cause the old images to be broken again after a few weeks?

I’m not certain if the photos disappear a second time after deleting & reinstalling.  It seemed to correct the problem when the app was first deleted/reinstalled, but not so on the following time.  I haven’t kept track of which photos remain active and which have disappeared.  Delete/reinstall today did refresh all photos.  I’ll try to note disappearing photos as they occur in the future.  

> which network (mobile service provider / WiFi / VPN / proxy) were you connected to when you reproduce the issue? If your Mattermost instance is publicly hosted, can you please confirm that you are able to connect to the mobile service provider and reproduce the problem too?

Happens on both mobile and WiFi

Thanks!

**Comment by kernandreas** [comment] 2020-07-24 12:43
Ich can report the same problem on my iPhone with version 1.33.1. Not a single image is visible.
My iPad with version 1.28.0 has this behaviour for some images.
All of them are visible in the web and Mac client.

**Comment by darkpiv** [comment] 2020-08-10 03:51
I'm having the same problems on iOS devices, quite rare and hard to reproduce. Delete the app does solve but it'll happen.

**Comment by jasonblais** [comment] 2021-08-21 18:21
@ahmaddanialmohd Would you have any guidance on how we might be able to troubleshoot this further?

@kernandreas @darkpiv Can you help share what iPhone and iOS version do you have? Have you recently seen this issue (cc @madhermit as well whether you've still seen this issue occur)

**Comment by ahmaddanialmohd** [comment] 2021-08-23 00:27
@jasonblais I think it is best to get the mobile team involved since it is very specific to that. 

@enahum @migbot @avinashlng1080 Have you encountered something like this before?

**Comment by enahum** [comment] 2021-08-23 00:29
@ahmaddanialmohd in my case, not ever.

**Comment by larkox** [comment] 2023-01-10 17:02
Closing due to the age of the issue. If you are still seeing this issue in V2, feel free to reopen it.

**Closed by larkox** 2023-01-10 17:02 UTC
