### ISSUE TITLE
iOS app crashes when uploading an image

### ISSUE THREAD

**Issue by sils** [mattermost/mattermost-mobile#1349] opened 2018-01-12 09:36 UTC
#### Summary

I have a client who uses the iOS app and reports that the app crashes every time when he wants to upload an image.

#### Environment Information

- Device Name: unknown
- OS Version: unknown
- Mattermost App Version: unknown, installed late december probably
- Mattermost Server Version: Version: 4.4.0  (4.4.3)

#### Steps to reproduce

Open app, open private channel to a person, choose an image

#### Expected behavior

Image should be uploaded

#### Observed behavior

App crashes

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by enahum** [comment] 2018-01-12 11:27
@sils please try and find out the version of the app and OS

**Comment by sils** [comment] 2018-01-12 12:14
App version: 1.5.1.
iOS 11.2.1

**Comment by enahum** [comment] 2018-01-23 13:47
@sils sadly I cannot repro this issue.

I'm able to upload images to public, private, direct and group channels without a problem.

Do you have an idea of the size in px and mb of the image?

**Comment by hydrapolic** [comment] 2018-02-08 05:41
I can too confirm, but it seems to happen rather randomly. I had the phone on for some time, took a picture and tried to send it and the app crashed. The next time started it went just fine. I also had reports from other colleagues that the picture upload stuck (endless spinner on thumbnail).

ios 11.2.2
Mattermost Team Edition 4.6.1
App version 1.6.0

**Comment by enahum** [comment] 2018-02-18 13:49
Wondering if this happen cause of a network glitch while uploading the image

**Comment by hydrapolic** [comment] 2018-02-18 16:51
Don't think so,it happened for various people on different ios devices/networks :-/

**Comment by lindy65** [comment] 2018-04-18 08:01
Hi @sils @hydrapolic 

I'm not able to reproduce this issue on the [latest version of the iOS app](https://about.mattermost.com/download/#mattermostApps) and Mattermost server v4.9 (released April 16th).

I'm going to close this issue off here for now but if you can still reproduce after [upgrading to the latest versions](https://about.mattermost.com/download/), please feel free to open a new issue with reproduction steps.

**Closed by lindy65** 2018-04-18 08:01 UTC
