### ISSUE TITLE
No messages appears in the chat window

### ISSUE THREAD

**Issue by a1tavista** [mattermost/mattermost-mobile#733] opened 2017-07-11 16:00 UTC
#### Summary
The messages doesn't appears in the chat window, when its seems to be loaded from server.

#### Environment Information

- Device Name: Huawei P9 Lite (VNS-L21)
- OS Version: Android 7.0
- Mattermost App Version: 1.0 (Build 39)
- Mattermost Server Version: 3.10.0

#### Steps to reproduce
1. Open the application
2. Choose any channel that you like 
3. After this you will see loading stub:

![image](https://user-images.githubusercontent.com/8191308/28077675-1acc5e46-666b-11e7-8b25-1861cbfe0b03.png)

#### Expected behavior
After the loading (when the loading stub disappears) I expect to see messages that was been loaded from the server.

#### Observed behavior
I see the empty screen.

![image](https://user-images.githubusercontent.com/8191308/28077667-14dbd3c2-666b-11e7-8b35-a7830dc3a1ce.png)

**Comment by michalcila** [comment] 2017-07-11 18:39
I'm facing the same issue.

**Environment Information**

- Device Name: Huawei Nova (CAN-L11)
- OS Version: Android 7.0
- Mattermost App Version: 1.0 (Build 39)
- Mattermost Server Version: 3.10.0

**Comment by philipkozeny** [comment] 2017-07-11 22:07
Same here

* Device Name: Huawei P9
* OS Version: Android 7.0
* Mattermost App Version: 1.0 (Build 39)
* Mattermost Server Version: 3.10.0

**Comment by chrispetsos** [comment] 2017-07-12 08:08
Same here

- Device Name: Huawei P10 Lite
- OS Version: Android 7.0
- Mattermost App Version: 1.0 (Build 39)
- Mattermost Server Version: 3.10.0

**Comment by lfbrock** [comment] 2017-07-12 15:32
Hi @a1tavista @philipkozeny @chrispetsos @michalcila 

1. Would anyone have additional details about your server set up? Is it using self-signed SSL certificates? 
2. Can you try signing up to https://pre-release.mattermost.com/login, and try to connect to that site using your mobile app to see if it works?

**Comment by a1tavista** [comment] 2017-07-12 17:35
1. We use MM with GitLab together. We use Let's encrypt SSL certificate.

2. So, the same issue with pre-release.mattermost.com, nothing appears in the chat window.

I have an though that this issue appears only on Huawei devices (as we can see in the comments above).

**Comment by michalcila** [comment] 2017-07-12 18:12
1. We use GeoTrust signed certificate, running on VM with Ubuntu Server 16.04 and use nginx proxy according to the documentation.
2. The same issue with pre-release.mattermost.com

**Comment by philipkozeny** [comment] 2017-07-12 18:24
1. let’s Encrypt with the official docker image
2. Same

**Comment by uetam** [comment] 2017-07-12 20:21
Same here

Device Name: Huawei P9 Lite
OS Version: Android 7.0
Mattermost App Version: 1.0 (Build 39)
Mattermost Server Version: 3.10.0 + nginx proxy using official documentation config file + letsencrypt certificate

**Comment by chrispetsos** [comment] 2017-07-13 06:01
1. We use proper signed certificates.
2. Still no messages in pre-release.mattermost.com Reception channel.

**Comment by lfbrock** [comment] 2017-07-13 23:30
Thanks everyone! 

As @a1tavista mentioned it does seem like it's an issue with the Huawei devices, we're trying to track down what could be causing it. Thanks for all the help with testing. 

If anyone is able to build and run the app from source, that might help us figure out the cause, otherwise hopefully we'll be able to get a device soon to try it ourselves

**Comment by erazipav** [comment] 2017-07-14 08:46
Works for me! App works perefctly.

Device: Huawei P8 Lite
OS Version: Android 6.0
Mattermost App Version: 1.0 (Build 39)
Mattermost Server Version: 3.10.0

**Comment by seanvree** [comment] 2017-07-14 11:31
I'm having this issue as well. It's weird because I still get push messages, but I can't connect to the channel. I just get a blank screen in the app. 

https://forum.mattermost.org/t/mobile-app-sends-notifications-but-cant-connect-to-server-winx64-android/3476/8

Server:
Version: 3.10.0
Database: MySQL
OS: Win10E 1703 x64
Configured for SSL

Mobile:
Platform: Android Samsung S7
Android 7.0
App Ver: 2017 (Beta) / also tried stable

**Comment by enahum** [comment] 2017-07-14 13:32
Ok guys is any of you who are having trouble to load the posts in the channel able to build the app yourselves and help us debug?

don't really know if this is a Huawei specific issue on Android 7 or an Android 7.0 specific issue.

The only way I can test this is with a emulator which I'm going to try in a few minutes and report back, but it would be of great help if some of you could build and run the app in your phones

**Comment by enahum** [comment] 2017-07-14 13:40
On more thing are you using EMUI or a particular ROM?

**Comment by philipkozeny** [comment] 2017-07-14 13:49
@enahum Official EMUI Rom, trying to run it from source now ...

**Comment by uetam** [comment] 2017-07-14 16:17
@enahum: Official EMUI 5.0

**Comment by michalcila** [comment] 2017-07-15 10:42
@enahum Official EMUI 5.0

**Comment by enahum** [comment] 2017-07-15 14:40
Guys it seems that we solved the issue can you try installing this apk https://www.dropbox.com/s/7bq54pisv1cbu15/app-release.apk?dl=0 It will be available on the next beta build amd obviously for the next release.

**Comment by michalcila** [comment] 2017-07-15 14:44
@enahum Awesome, it works! Thanks!

**Comment by uetam** [comment] 2017-07-16 09:18
@enahum: Works perfectly

**Comment by seanvree** [comment] 2017-07-16 12:07
@enahum  - This, unfortunately, didn't work for me.  I uninstalled the MM app, then side-loaded it with the one posted above.  I was able to initially sign into the server, and I it was working great for a couple hours...but then I got the white screen again.  ScreenShot:

![mmblankchannel](https://user-images.githubusercontent.com/8906637/28247408-a81e48b4-69e4-11e7-86cb-390243b59642.png)

**Comment by a1tavista** [comment] 2017-07-17 04:43
@enahum, your fix works for me, thank you!

**Comment by enahum** [comment] 2017-07-22 08:08
Hey guys there is a dot release now available in the google store that includes this fix, feel free to use that one, im going to close this issue but if somehow it happens again just re-open it

**Closed by enahum** 2017-07-22 08:08 UTC

**Comment by seanvree** [comment] 2017-07-22 16:50
@enahum  - what is "dot release" Pardon my noobness.
