### ISSUE TITLE
iPadOS 14: Mattermost notification badge shows non-existent unread messages

### ISSUE THREAD

**Issue by adf-patrickha** [mattermost/mattermost-mobile#5401] opened 2021-05-21 15:22 UTC
#### Summary
The Mattermost app reports unread messages in the app overview (notification badge) even though there are none.

### Environment Information
  - Device Name: iPad
  - OS Version: iPadOS 14.4.2
  - Mattermost App Version: 1.42.1
  - Mattermost Server Version: 5.31.4

#### Steps to reproduce
It's hard to reproduce. It happens one some devices and on some it doesn't. Event though they use the same device model, OS version and app version.

#### Observed behavior (that appears unintentional)
All messages are marked as read inside the app, but the app overview still shows unread messages:
![2021-05-21_17-14](https://user-images.githubusercontent.com/84573341/119160066-2c6a8980-ba58-11eb-9fd1-05cedd436b41.png)
Will add an additional screen recording as soon as the user confirms that we can use it in regards of privacy reasons.

**Comment by amyblais** [comment] 2021-05-21 16:17
@adf-patrickha Does re-installing the app help? Or logging out and back in?
Does this also repro on the latest v1.43 app version?

**Comment by adf-patrickha** [comment] 2021-05-21 16:44
> @adf-patrickha Does re-installing the app help? Or logging out and back in?

A reinstallation and logging out/in did both not solve the issue. 

> Does this also repro on the latest v1.43 app version?

We only deploy version 1.42 yet (MDM). I don't know if the newer version will be deployed in the near future. Is something issue-related mentioned in the changelog of v1.43?

**Comment by amyblais** [comment] 2021-05-21 17:06
@josephbaylon Does this repro for you?

**Comment by josephbaylon** [comment] 2021-05-21 17:25
@amyblais @adf-patrickha I'm unable to reproduce the issue on v1.43. Maybe try upgrading to 1.43 and see if you still encounter the issue. Thanks

**Comment by adf-patrickha** [comment] 2021-05-25 14:15
Screen recording by the user (you can ignore the audio): 
https://user-images.githubusercontent.com/84573341/119513126-3c45de80-bd74-11eb-8aa1-09cf1ecb82c6.mp4

AFAIK the user does nothing wrong and the issue is iPadOS or app related.

**Comment by amyblais** [comment] 2021-05-26 12:21
@enahum Would you have any additional tips for this?

**Comment by enahum** [comment] 2021-05-26 13:41
Video is not playing for me.

**Comment by adf-patrickha** [comment] 2021-05-26 13:43
> Video is not playing for me.

@enahum This is a GitHub issue. Just get the video via wget or copy the URL to VLC for example.

**Comment by enahum** [comment] 2021-05-26 13:53
The video does not show, but is there a notification present in the iPad notification center, that could be why the badge does not clear.

Even thought the above is true, this is still a bug.
cc: @amyblais

**Comment by amyblais** [comment] 2021-05-26 14:01
Opened a ticket: https://mattermost.atlassian.net/browse/MM-36046.

**Comment by amyblais** [comment] 2021-09-07 18:04
Closing, this was fixed in v1.44 release,

**Closed by amyblais** 2021-09-07 18:04 UTC
