### ISSUE TITLE
Timestamp of messages are not shown in local timezone

### ISSUE THREAD

**Issue by danleepw** [mattermost/mattermost-mobile#1935] opened 2018-07-19 02:37 UTC
The timestamp of messages are not shown in local timezone.

Server Version: 4.10.0 (Build 4.10.1)
App Version: 1.10.0 (Build 127)
App Platform: android

#### Expected behavior
The timestamp of messages are shown in local timezone

#### Observed behavior
The timestamp of messages are shown in UTC

**Comment by amyblais** [comment] 2018-07-19 12:41
Hi @danleepw!

This might be due to a new Timezone feature that was added. Can you go to Account Settings > Display > Timezone and check what the timezone is set to? (You might need to do this on browser / webapp)

**Comment by danleepw** [comment] 2018-07-19 14:57
Hi @amyblais 

I can't find this setting in mattermost on browser

My Mattermost server version is 4.10.1

**Comment by amyblais** [comment] 2018-07-19 15:04
Hi @danleepw! The timezone feature is available on 4.10 - it's possible that it has been disabled by your System Admin in the Console. Here is the setting: https://docs.mattermost.com/administration/config-settings.html#timezone.

Would you be able to ask an Admin on your system to check if that setting is enabled or disabled?

**Comment by danleepw** [comment] 2018-07-19 15:22
Hi @amyblais ,

My mattermost web interface is showing correct timezone without any setting. It seems the web and mobile behavior are not in-sync

**Comment by amyblais** [comment] 2018-07-19 15:58
I checked with the team about the new timezone feature and one reply was:

"It is picking the timezone automatically based on device settings.  My guess is that the user has OS timezone preferences that do not match what he's expecting. Because it's getting locale data from the OS. Also worth noting that his desktop/webapp can play a role. If the locale settings is different from mobile they would then update. This is an edge case but seems very unlikely of it occurring. If this is an issue for the user, he can set the timezone manually and it would not update."

Let me know if this sounds like it could apply in your case? If not, let me know and we will help further troubleshoot this.

**Comment by danleepw** [comment] 2018-07-19 17:51
I have a message which was sent at GMT 16:11. Then, I tried to manually change my android phone to different timezones. Here are the timestamps shown:

London (GMT +1, British Summer Time) -> 17:11
Hong Kong (GMT +8, Kong Kong Standard Time) -> 16:11 
Toyko (GMT +9, Japan Standard Time) -> 01:11
Seoul (GMT +9, Korean Standard Time) -> 16:11
Sydney (GMT +10, Australian Eastern Standard Time) -> 16:11

It seems that the timestamp is shown incorrectly in some timezones

**Comment by dmittr** [comment] 2018-07-19 21:31
Looks like time calculation is wrong. 

**My setup**
Server (CentOS 7.4, Mattermost v. 5.1.0) timezone
```
timedatectl|grep zone
Time zone: Asia/Vladivostok (+10, +1000)
```
Desktop client v. 4.1.2 (Ubuntu) - same time-zone settings as server-side
Mobile app v. 1.10.0 - same time-zone settings as server-side
**What i see**
Desktop client - correct time (19:54, 21:56) https://i.imgur.com/3YldI2M.png
Mobile client - wrong time (9:54, 11:56) https://i.imgur.com/HQf92r6.png

Time shifted to 10 hrs. back instead of 0 (while the same timezone).

**Comment by enahum** [comment] 2018-07-20 07:31
Fyi @miguelespinoza

**Comment by amyblais** [comment] 2018-07-26 18:10
Hi @dmittr - Have you enabled the [experimental timezone](https://docs.mattermost.com/administration/config-settings.html#timezone) settings on your server?

**Comment by dmittr** [comment] 2018-08-01 14:26
Thanks to @amyblais for pointing me solution. After setting ExperimentalTimezone mobile clients able to turn off automatic time-zone.

**Comment by danleepw** [comment] 2018-08-01 14:38
hi @amyblais , could you give us more info about that? So, the only solution is to enable  experimental timezone settings on server?

**Comment by amyblais** [comment] 2018-08-01 14:42
It could be a solution, would you be able to try it out? If it doesn't help resolve the issue, can you help with details on your Android OS version?

**Comment by danleepw** [comment] 2018-08-01 15:14
i can't try that setting on server. Actually, that issue just occurred after upgrading mattermost app. Is it also related to server-side? My Android version is 8.0.0

**Comment by danleepw** [comment] 2018-08-01 15:53
@amyblais , sorry that I don't quite understand the situation. If the feature is disabled by default, why does it bring the impact when using with server which doesn't enable the "experimental timezone"? On the other hand, if "experimental timezone" must be enabled on server in order to make the app correctly working, then it shouldn't be "experimental", right?

**Comment by ffuentes** [comment] 2018-08-10 23:53
Confirmed too in app v1.11.0 build 129.

Server Version: 5.1.0 (Build 5.1.1)
App Version: 1.10.0 (Build 129)
App Platform: android

**Comment by sjstyle** [comment] 2018-08-14 11:15
Server version 4.7.3 also makes happens.
App Version 1.10.0 shows wrong timezone (in android)
App Version 1.9.0 shows correct timezone.

**Comment by miguelespinoza** [comment] 2018-08-14 17:09
Hey everyone, sorry for the late response.
I agree, when an experimental feature is disabled by default it should not impact the client.
Seems an issue occurred specifically to Android devices.  

@enahum, it would be cool if you could add a link to the issue that fixed it so I can take a look at what was missed.

**Comment by enahum** [comment] 2018-08-14 17:10
https://github.com/mattermost/mattermost-mobile/pull/1982

the problem is the toDateLocaleString

**Comment by amyblais** [comment] 2018-08-21 12:01
Great to hear it, I'll close this Issue for now then,

**Closed by amyblais** 2018-08-21 12:01 UTC

**Comment by bwo** [comment] 2019-11-05 14:41
this still happens for me on linux. version 4.3.1.
