### ISSUE TITLE
Upload File Size Limit from Server ignored

### ISSUE THREAD

**Issue by eni23** [mattermost/mattermost-mobile#4263] opened 2020-05-05 09:48 UTC
## Summary

If change the setting `MaxFileSize` in `config.json` to eg. 128MB  the app ignores the setting and does not allow to upload bigger files. Works in web interface.

#### Environment Information

- Device Name: Apple iPad Pro
- OS Version: 13.4.1
- Mattermost App Version: 1.30 but also tested with older versions
- Mattermost Server Version: 5.9 LTS

#### Steps to reproduce
Change `MaxFileSize` in `config.json` on server and restart Mattermost. Try to upload a file bigger than the default 50MB and see it fail. Works in Mattermost web. 

#### Expected behavior
Upload of files bigger than the default in app and get the actual server upload limit.

#### Observed behavior
Cannot upload bigger files.

**Comment by enahum** [comment] 2020-05-05 12:06
@eni23 I just tested and the mobile app is getting the changed value for `MaxFileSize` when updated from the system console.

The updated value should be set either if the app is running in the foreground or with the next request to the server.

Can you please try again and report back any details to determine if there is an actual bug with this.

Thanks.

**Comment by eni23** [comment] 2020-05-05 12:31
We are running in HA Mode and thus are not able to change the value over the system console. I just tried to change the value again (change config.json and restart all 3 nodes) with an app open, but still the same, app does not allow to upload files bigger than ~50MB

**Comment by eni23** [comment] 2020-05-06 08:55
Addition: If curl'ing  `https://chat.example.com/api/v4/config/client?format=old` we will get the updated setting which is ignored by the app.

**Comment by enahum** [comment] 2020-05-06 09:05
@saturninoabril can you help verify this?

**Comment by saturninoabril** [comment] 2020-05-06 09:06
@enahum Sure, will do.

**Comment by smirta** [comment] 2020-05-06 10:23
Additional info: It works as expected in mattermost-desktop on linux.

**Comment by saturninoabril** [comment] 2020-05-06 13:48
I tested on ESR (LTS) test server and the changes made to max file size (set to 100MB) took effect to clients including iOS App (tried on 1.29 and 1.30) which allowed me to upload 94MB file. There's a file upload error on all clients but it's probably due to nginx setting (``client_max_body_size 50M``). I'm doing a separate setup where I could change such nginx value - will update on it.

**Comment by saturninoabril** [comment] 2020-05-06 16:29
@eni23 @smirta Works for me.  I couldn't repro the one you're seeing.  Would be helpful if you could give more details -- fail log/message on client or server (is it "File above {size} cannot be uploaded..."), file type (same issue on other file?).

**Comment by smirta** [comment] 2020-05-06 20:39
I can only tell you from a user's perspective. If I'm uploading a file bigger than 50MB and smaller than 128 on iPadOS or Android, there is no error message. The file just appears as a failed upload and when the "post" button is pressed, some error saying that the attachment failed to upload. 


![image](https://github.com/smirta/temp/raw/master/Screenshot_2020-05-06_at_22.31.01.png)

**Comment by eni23** [comment] 2020-05-07 09:29
The server does not logs anything, looks like the request is not even passed to the server. If logging out and login to the iPad we get the following Message:
![Bildschirmfoto 2020-05-07 um 11 18 55](https://user-images.githubusercontent.com/3918506/81277920-54f23200-9055-11ea-8fa4-08e331823f60.png)

 
As mentioned, curl to: https://chat.example.com/api/v4/config/client?format=old gives the correct value:
```
[...]
  "MaxFileSize": "134217728"
[...]
```

Also, the (read only since in HA-Mode) admin console shows the correct value:
![Screenshot (3)](https://user-images.githubusercontent.com/3918506/81278486-05f8cc80-9056-11ea-989d-2f124458f820.png)

**Comment by eni23** [comment] 2020-05-07 10:57
OK, additional Info: we use your antivirus-plugin: https://github.com/mattermost/mattermost-plugin-antivirus

If disabling the plugin, the upload works perfectly. Looks like the mobile app does not wait on an OK response from server, while the web app does.

**Comment by saturninoabril** [comment] 2020-05-07 13:14
Thanks for the infos.  Unfortunately, I couldn't reproduced. There seemed to be 2 different issues here and those issues are actually not supporting each other:
- [orig from @eni23] - getting not allowed to upload file between 50-128MB after changing max file size -- nice to see this working now on your side but it might not be related directly to anti-virus plugin. It could be due to config change sending to all nodes in cluster after disabling the said plugin. Could you try purging all cache at `/admin_console/general/configuration` and see if it has the same effect?
- [from @smirta] allowed to upload file between 50-128MB but failed in the process -- if using reverse proxy like nginx, please check if it allows uploading of such size and within timeout limits. (Although, per recent comment above "the upload works perfectly")

**Comment by larkox** [comment] 2023-01-10 16:29
Closing due to the age of the ticket, and that it seems to be solved.

**Closed by larkox** 2023-01-10 16:29 UTC
