### ISSUE TITLE
Loading Spinner doesn't go away.

### ISSUE THREAD

**Issue by SnowShock35** [mattermost/mattermost-mobile#1050] opened 2017-10-23 19:23 UTC
#### Summary

Loading symbol won't go away no matter what I try. It just keeps spinning. Tried changing channels and force refreshing it but no luck.

--

#### Environment Information

- Device Name: OnePlus 5
- OS Version: Oxygen 4.5.13 (Android 7.1.1)
- Mattermost App Version: 1.0 (Build 39)
- Mattermost Server Version: 4.1.0 (Build 4.1.0)

#### Steps to reproduce

1. Open App
2. Go to any channel
3. Channel content will load and yet the loading animation circle just stays there even though content is loaded.

#### Expected behavior
The spinner goes away when the page is loaded.

#### Observed behavior
The spinner just keeps going... and going and going and going. 

![Imgur](https://i.imgur.com/7aXhm9Z.png)
![Imgur](https://i.imgur.com/kc1UPaa.png)

#### Possible fixes

Turning it off and on again didn't work 😢

**Comment by enahum** [comment] 2017-10-25 15:51
Hi @SnowShock35 can I ask you to update your app, the current version deployed to the Google Play Store is version 1.3 build 57

**Comment by SnowShock35** [comment] 2017-10-27 12:37
Hi. Updating to this version did not fix my issue.

**Comment by lfbrock** [comment] 2017-11-07 17:50
Hi @SnowShock35 - can you try deleting and re-installing the app (newest is v1.4) to see if the issue still reproduces? 

And if it does, can you try going to the Settings menu > Report a problem, and share any errors you see there?

**Comment by el-moalo-loco** [comment] 2017-11-30 09:51
Could this be related to #1106? To me this looks like the same problem just on a different OS...

**Comment by lindy65** [comment] 2018-04-18 19:11
This issue is fixed in the latest version.  Please upgrade [here](https://about.mattermost.com/download/#mattermostApps).

**Closed by lindy65** 2018-04-18 19:11 UTC
