### ISSUE TITLE
Crash when clicking the mobile settings button

### ISSUE THREAD

**Issue by CreeperLava** [mattermost/mattermost-mobile#1062] opened 2017-10-25 10:14 UTC
#### Summary

Crash when clicking the mobile settings button.

#### Environment Information

Server Version: 4.2.0 (Build 4.2.0)
App Version: 1.3.0 (Build 57)
App Platform: android
- Device Name: 
- OS Version: 
- Mattermost App Version: 
- Mattermost Server Version:

#### Steps to reproduce
Click the button.

#### Expected behavior
Open the settings panel.

#### Observed behavior
App closes / crashes.

**Comment by enahum** [comment] 2017-10-25 15:44
duplicate of #1014

**Closed by enahum** 2017-10-25 15:44 UTC
