### ISSUE TITLE
URLs are broken in Android

### ISSUE THREAD

**Issue by s1shed** [mattermost/mattermost-mobile#7002] opened 2023-01-23 15:22 UTC
#### Summary
Links in message are resolved incorrectly, at least on a server using a subpath.

### Environment Information
  - Device Name: Pixel 6
  - OS Version: Android 13
  - Mattermost App Version: 2.0.0
  - Mattermost Server Version: 7.7.1

#### Steps to reproduce
1. self-hosted server is available using a path https://host.tld/mm/. 
2.  receive a message containing a URL, any URL, e.g. https://github.com/mattermost/mattermost-mobile/issues/new
3. tap the URL

#### Expected behavior
The tapped URL should open in the browser.

#### Observed behavior (that appears unintentional)
The URL that opens is invalid. Using my example URLs above the URL that opens in the browser is https://host.tld/mmhttps://github.com/mattermost/mattermost-mobile/issues/new

**Comment by amyblais** [comment] 2023-01-23 15:35
@jgilliam17 Are you able to reproduce this on Android?

**Comment by s1shed** [comment] 2023-01-23 16:06
The behaviour is consistent for me with all URLs. This was not a problem with the previous releases of the server or client.  

This works correctly in the desktop client (v5.2.2). Also, if I tap, hold, and select "Copy URL", this URL is correct.

![kuva](https://user-images.githubusercontent.com/8793762/214087366-99aa2ba6-205a-4f61-9ef3-cf0a3af60677.png)

**Comment by amyblais** [comment] 2023-01-23 16:18
Opened https://mattermost.atlassian.net/browse/MM-49850.

**Comment by jgilliam17** [comment] 2023-01-23 16:56
@amyblais I am not able to reproduce "page not found error", but I do see that the link is not opening correctly. It is opening in the browser as a redirect to the server configured in the app, logging in on the browser shows "team not found" screen. I'll add my comment to the ticket.

**Comment by Willyfrog** [comment] 2023-01-30 10:48
Fixed in https://github.com/mattermost/mattermost-mobile/pull/7010

**Closed** 2023-02-09 13:48 UTC
Labels: Bug Report/Open
