### ISSUE TITLE
Can't sign in when there is a trailing slash in server URL

### ISSUE THREAD

**Issue by sedrubal** [mattermost/mattermost-mobile#701] opened 2017-07-04 09:15 UTC
#### Summary
If there is a slash `/` at the end of the server URL you can't sign in to Mattermost (or at least not if you are using GitLab oauth with 2fa). After entering the credentials and the 2fa code you just see

```json
{"status": "ok"}
```

but you can't continue.

#### Environment Information

- Device Name: Nexus 5
- OS Version: Android 7.1.2 (LineageOS)
- Mattermost App Version: 1.0
- Mattermost Server Version: 3.10.0
- GitLab Version: 9.3.3

#### Steps to reproduce
- set up Mattermost using GitLab oauth and 2fa
- install Mattermost RN and open it
- enter the server name: `https://mattermost.my-domain.com/`
- proceed and choose GitLab login
- enter credentials
- enter 2fa code

#### Expected behavior
Mattermost channels and so on should be visible.

#### Observed behavior
You just see `{"status": "ok"}`.
![file download from mattermost](https://user-images.githubusercontent.com/5571650/27824044-712c9faa-60ab-11e7-9559-011c0fa7eb53.jpg)

#### Possible fixes
A workaround is to remove the trailing slash. The app could do the same. #315 looks related.

Thanks to @kingfisher77 for pointing me in the right direction in #355.

**Comment by enahum** [comment] 2017-07-04 20:39
I really don't think the problem is with the trailing slashes cause we remove them here  https://github.com/mattermost/mattermost-mobile/blob/master/app/screens/select_server/select_server.js#L127 does it work if you enter the server url without the trailing slash?

**Comment by sedrubal** [comment] 2017-07-06 12:19
Yes it does work:

![anim](https://user-images.githubusercontent.com/5571650/27910605-20487da0-6256-11e7-934f-623a798bff73.gif)

**Comment by lfbrock** [comment] 2017-07-13 16:09
@enahum - this is the same issue reported on the blog post: 

https://about.mattermost.com/mattermost-2nd-gen-mobile-apps-released-emm-compatible-starting-with-blackberry-dynamics/#comment-3414850522

**Comment by enahum** [comment] 2017-07-22 08:13
Closing voia #754

**Closed by enahum** 2017-07-22 08:13 UTC

**Comment by jcelerier** [comment] 2018-04-04 07:15
I'm having the same problem but my server does not have a trailing slash :(

**Comment by sherpya** [comment] 2018-08-08 16:33
still happens with mattermost 5.1.0 and android app 1.10.0, It happens if I enable email login and gitlab together, temporary disabling email login made my app login work

**Comment by enahum** [comment] 2018-08-08 16:44
Can you make sure your server url and the redirect url from your oauth matches?
