### ISSUE TITLE
Archived teams reappear in selector

### ISSUE THREAD

**Issue by licaon-kter** [mattermost/mattermost-mobile#2593] opened 2019-02-25 07:08 UTC
Android AOSP 9, 1.16.1 on server 5.8.0

There's a high chance that old archived teams reappear and can be switched to.

Once that happens the teams selector disappears and you are stuck there needing to logout and login again.

There is no error standing out in logcat.

Repro steps (not sure these trigger it every time):
* open app and login as an admin
* no teams selector available
* open random private channel
* touch one post to enter single post mode (or whatever is that called when you only see that post and its replies)
* hit back arrow on title bar
* hit burger menu on title bar
* see the teams selector with active and archived teams
* select archived team

**Comment by amyblais** [comment] 2019-02-25 19:30
Hi @licaon-kter,

How are you archiving the team?  Or do you mean archived channels?

**Comment by licaon-kter** [comment] 2019-02-25 19:49
`mattermost team archive`

**Comment by enahum** [comment] 2019-03-22 05:40
@amyblais this seems to be an issue with the API endpoint that does not returned deleted/archived teams.

When the app is closed or the WebSocket disconnected the app does not know anything about the archived/deleted team. When the app is re-opened it contains offline data with the team that was deleted and when the teams are fetch from the server that endpoint does not return any information about the team being archived thus no changes to the data in the device.

The above will cause that any other request made will fail as the team is no longer available.

There are two options to fix this:
1. Make the endpoint to return data about deleted/archived teams and update the app data accordingly.
2. Replace all the teams when those are fetch. This one will probably have other ramifications.

**Comment by amyblais** [comment] 2019-03-22 14:01
@enahum Thank you, I was waiting on QAs to test this. I opened a ticket here: https://mattermost.atlassian.net/browse/MM-14697.

**Comment by licaon-kter** [comment] 2019-05-15 17:02
@amyblais Your QA hasn't repro? Still an issue in 1.19.0, clean app install.

**Comment by amyblais** [comment] 2019-05-15 17:06
@licaon-kter The Jira ticket linked above is still open and under dev investigation.

**Comment by lindalumitchell** [comment] 2019-07-25 23:46
@licaon-kter I have rediscovered the Jira ticket for this issue; apologies that it was so long ago. We have tried again to reproduce but couldn't. Is this still an active issue for you?

**Comment by licaon-kter** [comment] 2019-07-26 04:52
Yup, still an issue on 1.21.1 w/ server 5.13.0

![archivedteams1211](https://user-images.githubusercontent.com/2282799/61926626-e67a3280-af60-11e9-87c1-59772f7808ab.jpg)

(_those last two were archived a long time ago_)

**Comment by lindalumitchell** [comment] 2019-07-26 05:39
Thanks for the info! Turns out we just happened to repro this since my post, while investigating another bug. I'll reopen the Jira ticket and we'll track progress there. https://mattermost.atlassian.net/browse/MM-14697

Appreciate your patience and your help!

**Comment by amyblais** [comment] 2019-08-21 13:51
Closing as this was fixed in v1.22.

**Closed by amyblais** 2019-08-21 13:51 UTC
