### ISSUE TITLE
Problem with Mattermost React Native ios app

### ISSUE THREAD

**Issue by KrzysztofSadowski1** [mattermost/mattermost-mobile#776] opened 2017-07-24 15:04 UTC
#### Summary
On iOS client I have still connecting label.

- Device Name: Iphone 7 plus
- OS Version: 10.3.2 (14F89)
- Mattermost App Version: 1.0.1 (Build 41)
- Mattermost Server Version: 3.10.0

#### Steps to reproduce
Log in.
The "Connection" label on the top is always on (grey background) and it's not disappearing.
The channels and DM are not refreshing on list.

#### Expected behavior
After logging in MM should connect and the label should disappear.

#### Observed behavior
Is something wrong with server configuration? 
Also it's not refreshing updates on channels and dm. 
I found in new version unread threads listed always on top - great thing! But this list isn't refreshing on my app. 
I have also classic app installed and everything is working fine on it (of course without last issue).
#### Environment Information
![image1](https://user-images.githubusercontent.com/30412718/28529887-146d3940-7092-11e7-8485-3369619c1200.png)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by enahum** [comment] 2017-07-24 18:19
duplicate of #742 

Please check your server reverse proxy configuration, I'm going to close this issue, please feel free to continue the discussion in #742

**Closed by enahum** 2017-07-24 18:19 UTC
