### ISSUE TITLE
Can't enter MFA token during login

### ISSUE THREAD

**Issue by fleaz** [mattermost/mattermost-mobile#7524] opened 2023-08-30 13:51 UTC
#### Summary
Keyboard disappears immediately when asked for MFA token during login.

### Environment Information
  - Device Name: Samsung Galaxy S23 Ultra
  - OS Version: Android 13
  - Mattermost App Version: 2.7.0
  - Mattermost Server Version: 7.8.7

#### Steps to reproduce
Install the app and try to login with an account that has MFA activated.

#### Expected behavior
The user should be able to enter their MFA token.

#### Observed behavior (that appears unintentional)
When clicking into the textbox to enter the token, the keyboard appears only for a splitsecond.

My colleague recorded a video of the weird behavior: [Video](https://dump.felixbreidenstein.de/mattermost_2fa_issue.mp4)

#### Already tried things to fix it
 * Reboot
 * Reinstall of the app
 * Reinstall of the whole phone

Best,
Felix

**Comment by amyblais** [comment] 2023-08-30 14:15
Does the workaround described here help https://forum.mattermost.com/t/can-not-log-in-android-app/16042/17?

**Comment by amyblais** [comment] 2023-09-22 16:25
We also have a related ticket open here https://mattermost.atlassian.net/browse/MM-53236.

**Comment by fleaz** [comment] 2023-10-13 14:28
Hey, sorry for the late reply.

> Does the workaround described here help https://forum.mattermost.com/t/can-not-log-in-android-app/16042/17?

No, sadly not. We provided the credentials manually by typing them into the fields with they keyboard.

> We also have a related ticket open here https://mattermost.atlassian.net/browse/MM-53236.

This is not the same bug we have. In the provided ticket, the whole MFA screen is just blank white. In my case (check video in first post) we get the normal MFA screen, but the keyboard is not staying open so we can't enter a token

**Comment by amyblais** [comment] 2023-10-13 17:32
Opened a separate ticket: https://mattermost.atlassian.net/browse/MM-54937.

**Comment by enahum** [comment] 2023-10-14 03:55
What keyboard does the phone have installed? Does it reproduce if you try gboard?

**Comment by enahum** [comment] 2023-10-18 14:06
@fleaz can you please tell me what keyboard are you using? Samsung, GBoard, SwiftKey, other? have you tried with another keyboard ? I'm afraid I cannot reproduce this issue and I need more details.

**Comment by amyblais** [comment] 2024-05-28 18:39
Closing for as our team hasn't been able to reproduce this,

**Closed by amyblais** 2024-05-28 18:39 UTC
Labels: Bug Report/Open
