### ISSUE TITLE
Mobile devices receive ghost notifications for already read messages

### ISSUE THREAD

**Issue by uusijani** [mattermost/mattermost-mobile#4753] opened 2020-08-29 17:07 UTC
#### Summary
Mobile devices receive "ghost" notifications for already read messages, when set to receive notifications "when Away or offline", and receiving user is set to be Away.

#### Steps to reproduce
1. Set "Mobile Push Notifications" to "Trigger push notifications when": "Away or offline" (and send "For all activity")
2. Using web interface on desktop, set your status to Away
3. (Still in the web interface) receive a message in the currently open channel (which immediately marks it read)

#### Expected behavior
Nothing happens on the mobile device (no notification).

#### Observed behavior (that appears unintentional) 
The mobile device receives a notification about the already read message. The notification immediately disappears. If you weren't looking at the device, you're left wondering why it alerted you.

#### Other info
If your status is set to Online instead of Away (at step 2), the mobile device receives no notification (as expected). If "Trigger push notifications when" is set to "Online, away or offline" (at step 1), the mobile device receives no notification irrespective of your Online/Away status (also as expected).

#### Environment Information
I'm self-hosting Mattermost 5.26.1 with self-hosted MMPNS 5.22.4. Mattermost Mobile is at version 1.34.0. My mobile devices have Android 10 (Samsung) and Android 7.1.2 (LineageOS 14.1).

I don't know if this is an issue with the client or the server; I can re-report against the latter if appropriate.

**Comment by enahum** [comment] 2020-08-30 03:21
@uusijani just as an FYI, the mobile app just receives the notification, does not send it, so I’m asking someone from the server team for them to check if its expected and someone from the webapp team to see if the messages should in fact be marked as read.

**Comment by esethna** [comment] 2020-09-03 16:03
@uusijani appreciate you reporting this, I've opened a ticket to address this, good find! https://mattermost.atlassian.net/browse/MM-28327

**Comment by agnivade** [comment] 2020-12-17 09:19
@uusijani - Unfortunately I am not able to reproduce this. In my case, I always get a notification which does not disappear, which is expected from the code from what I am seeing. The server checks the user status, and if it is set to away, sends a PN. That's it.

Unless you manually switch to the channel which got the message in the web interface, no "read message" event gets sent out, which makes the PN go away.

If you are still able to reproduce this, can you show me the server logs at a DEBUG level after the original post is created from the other user?

Although the functionality hasn't changed, but did you get a chance to upgrade to a newer version of Mattermost during this time? Just to root out any unrelated bug here.

**Comment by uusijani** [comment] 2020-12-18 08:26
Yes, this is still reproducible here with the current server (v5.29.1).

Here's the [server log](https://github.com/mattermost/mattermost-mobile/files/5714505/mm.log) and [MPNS log](https://github.com/mattermost/mattermost-mobile/files/5714506/mpns.log) during which

1. I switch debug level from error to debug
2. I send one "hello" message to a bot (from the web UI)
3. the bot responds with one message
4. I switch debug level from back to error

**Comment by agnivade** [comment] 2020-12-18 09:47
Hey @uusijani - thanks for getting back!

Couple of clarifications:
- You have manually set your status to away.
- Set "Mobile Push Notifications" to "Trigger push notifications when": "Away or offline" (and send "For all activity")
- Then you send a message to a bot
- The bot replies back
- You get a Push notification for the reply on your phone, which then immediately goes away

Is that accurate?

This log here: `Received HTTP request   {"method": "POST", "url": "/api/v4/channels/members/me/view", "request_id": "exrh9hqiaiyttexoqn7yytmhzw", "status_code": "200"}`, this is essentially telling the system to mark the channel as viewed, which will clear the push notification. So the webapp still counts that an activity from your side, which makes it clear the notification on your phone.

I am wondering if you can create a setup of userA and userB. Set userA's status to away and from a different window, login as userB, send a message to userA. And then check the notification on userA's phone. If the push notification still disappears, then please send us the logs.

**Comment by uusijani** [comment] 2020-12-18 13:22
Yup, your description of the issue is exactly right @agnivade, and thanks for looking into this!

I set up the two users in parallel windows. Sending a normal message as userB this way does not trigger the issue (I do get a notification on userA's phone, but it doesn't go away by itself), but that's because userA's window is (obviously) not active, since I'm typing in userB's window. The notification is only cleared once I activate userA's window.

But I *can* trigger the issue by using (for instance) `/echo 'hello A' 4` instead (as userB), then hopping on to activate userA's window during the 4-second delay, so that userA's window is active when receiving the message. That's the crucial bit: the receiver's window is active when receiving the message. If his status is 'Online', there's no push notification (as expected), but if it's 'Away', that's when I get the ghost notification.

Here's [server log](https://github.com/mattermost/mattermost-mobile/files/5715861/mattermost.log) and [MPNS log](https://github.com/mattermost/mattermost-mobile/files/5715863/mmp.log) during one minute where I first send a normal message, then (at about 30 seconds) using `/echo`.

**Comment by agnivade** [comment] 2020-12-18 16:33
Hey @uusijani - if the receiver's window is active, I think that's the right behavior. If a user is away, then they are meant to be "away". But if they are active, then the status should be "active".

From the server side, it is hard to _not_ send a push notification based on if you have set the status to "away" and left your desk (in which case a push notification is expected), and whether you have set the status to "away" and still active at your desk(which causes the ghost notification). The only way we know is when the webapp sends a viewChannel/createPost event, which marks a notification as read, and thereby clears the notification from your phone.

We can indeed come up with some hacks like if the last view event was within x seconds, and the status is away, do not send a push notification. But there are various edge-cases with it. What if you type something, and leave your desk, and get a message? According to this logic, you won't get any notification.

I think the current implementation plays it a bit safe by sending you messages, and relies on the user to correctly update their status to active/away instead.

Let me know your thoughts on this.

**Comment by uusijani** [comment] 2020-12-19 16:41
@agnivade Oh I see, so it's a result of conflicting indicators ("away" vs. being active) from the user. I'm trying to recalibrate my expectation based on this, but it's difficult.

My immediate thought is perhaps (in the problematic case) sending the notification, but then clearing it only once I start typing (typing appears to have an event associated with it, at least based on the logs) would be better than the immediately clearing ghost notification, but you're right, this is more complicated than immediately apparent.

Some UI/UX design wizardry would probably be needed to eliminate the possibility of mixed user signals, if at all possible. I don't have a good solution for now, so feel free to close the issue if you deem it appropriate.

**Comment by agnivade** [comment] 2020-12-19 18:09
It would be certainly _technically possible_ to clear it on the typing event. But the semantics of it gets really complicated IMO. What makes the typing event special, than let's say, a channel view event? The system assumes that the user can only look at a single place at one time. So if you are at the web client generating some activity, then you are not on your phone, so it makes sense to clear the notification on _any_ event, not just typing. That makes the overall semantics clear and simple to understand.

- If your status is active, you don't get any notifications.
- If your status is idle, you do get notifications.
- If you generate some events, while being idle, the system assumes you are back there again, and it clears the notifications. Which I think makes sense because you cannot look at two places at the same time.

In any case, there does not seem to be any bug with the system here. Perhaps only mismatched expectations. I will leave it to @esethna to decide if there is something that needs to change.

**Closed** 2021-01-11 23:07 UTC
