### ISSUE TITLE
Typing right after clicking send button doesn't clear the old message

### ISSUE THREAD

**Issue by xRahul** [mattermost/mattermost-mobile#3835] opened 2020-01-21 03:31 UTC
#### Summary
When you're sending a message to anyone, start typing right after clicking the send button and it will append to old message instead of clearing that and starting with a new one

#### Environment Information

- Device Name: Pixel 2 XL
- OS Version: Android 10
- Mattermost App Version: 1.26.2
- Mattermost Server Version: 5.19

#### Steps to reproduce
How can we reproduce the issue?
When you're sending a message to anyone, start typing right after clicking the send button and it will append to old message instead of clearing that and starting with a new one

#### Expected behavior
Either the textbox where you type the message also gets disabled until text clears, or clear text as soon as we click the send button.

#### Observed behavior
Text doesn't clear and so the 2nd message will get appended to the 1st message you've already sent but was left in the text box

#### Possible fixes
I think we are clearing text too late. Not sure why it doesn't get cleared if we start typing right after though
https://github.com/mattermost/mattermost-mobile/blob/ef0274cad85c664b835222b1674a733c3dbf42ee/app/components/post_textbox/post_textbox_base.js#L625

I don't have full context of how this happens, if someone knows and it is a small fix, let's fix before next version!

**Comment by amyblais** [comment] 2020-01-21 23:43
@xRahul Would you be open to testing this on v1.27.1 which will be available on the app stores in the next day or two and see if it still reproduces? You can also download an apk here if you want to: https://releases.mattermost.com/mattermost-mobile/1.27.1/260/Mattermost.apk,

**Comment by xRahul** [comment] 2020-01-22 03:18
@amyblais sure, I'll check. I've applied for the pre-release channel as I don't have access to any other MM channel right now to test this.

**Comment by xRahul** [comment] 2020-01-23 04:00
I've tried in the recently releaesd 1.27.1 version and ths issue is still there.

**Comment by amyblais** [comment] 2020-01-24 16:08
A ticket for this was opened here: https://mattermost.atlassian.net/browse/MM-22029.

**Comment by xRahul** [comment] 2020-03-17 05:45
Any update on when this will be picked up in the pipeline?

**Comment by chuttam** [comment] 2020-06-01 13:12
@xRahul The Post composition input area when through a significant overhaul in app versions 1.30  (April) and 1.31 (May). Consequently, I am unable to reproduce the trouble you were having. I too remember seeing similar behaviour around 1.27 and 1.28.

Would you be willing to install the most recent app store version and try this again? As seen in the screen grab below, posted messages clear the text input right away.

<img width="373" alt="Type right after posting" src="https://user-images.githubusercontent.com/887849/83412343-4c8cdd00-a3f0-11ea-854d-e5b115767e42.gif">

**Comment by jasonblais** [comment] 2021-08-21 18:47
@xRahul Thanks for reporting this issue to us! We released a fix for this issue with v1.34, released in August 2020.

Jira ticket for reference: https://mattermost.atlassian.net/browse/MM-22029

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Closed by jasonblais** 2021-08-21 18:47 UTC

**Comment by xRahul** [comment] 2021-08-31 11:55
Thank you!
