### ISSUE TITLE
Can't send standard emojis picked from autocomplete in mobile application.

### ISSUE THREAD

**Issue by SponToN83** [mattermost/mattermost-mobile#4582] opened 2020-07-17 09:56 UTC
Summary
Can't send standard MM emoji when it is picked from autocomplete picker.

Steps to reproduce
start typing :_NAME_OF_EMOJI
pick it from autocomplete picker.
Emoji is showed in input.
Send Emoji.
Emoji is showing with error after i and it is not delivered. Retrying makes no difference.
Custom emojis are working properly. One difference is that after picking custom emoji from picker instead of icon there is an alias typed :EMOJI_NAME:.
One more thing is that when standard emoji is just typed instead of picking from autocomplete it is also delivered properly.

Expected behavior
Standard Emoji picked after typing part of name is delivered properly.

Server side error:
{"level":"error","ts":1594929846.1196952,"caller":"mlog/log.go:175","msg":"Invalid or missing name parameter in request URL.","path":"/api/v4/emoji/autocomplete","request_id":"r71dss5uair9pyk9r1rrwad1qa","ip_addr":"XXX.XXX.XXX.XXX","user_id":"XXXXXXXXXXXXXXXXX","method":"GET","err_where":"Context","http_code":400,"err_details":""}

MM Version: 5.25.0
Mobile App: Android 1.31
Device: Samsung A71, Motorola One Vision (I think this is irrelevant)

**Comment by amyblais** [comment] 2020-07-17 12:45
@SponToN83 We are unable to reproduce this internally. Do you also see this on v1.33.1?

**Comment by SponToN83** [comment] 2020-07-17 13:11
Yes I have this version. 1.33.1 (Build 311).

**Comment by SponToN83** [comment] 2020-07-17 13:13
Reactions emoji picker is working ok.

**Comment by SponToN83** [comment] 2020-07-17 13:27
How can I help you with investigating this issue ? Do you need any more info ?

**Comment by amyblais** [comment] 2020-07-17 13:36
Are you able to reproduce this on different servers such as https://community.mattermost.com?

@josephbaylon Do you reproduce this?

**Comment by SponToN83** [comment] 2020-07-17 14:23
It looks ok on this server.

**Comment by amyblais** [comment] 2020-07-21 18:54
@SponToN83 Do you experience the same on browser?

**Comment by SponToN83** [comment] 2020-07-21 19:05
Only on mobile. On browser and windows application is ok

**Comment by amyblais** [comment] 2020-07-22 13:42
@SponToN83 Does it happen with all standard emojis or specific ones?

**Comment by SponToN83** [comment] 2020-07-22 14:27
I've tested it on several of theme and it was the same effect for all of them. It is weird that on community server it was ok. Maybe there is a problem with server installation / configuration.

**Comment by amyblais** [comment] 2020-07-22 20:44
Our support team may be able to help better - you can email them at feedback@mattermost.com.

**Comment by zxqdx** [comment] 2020-08-08 02:03
We use Teams Edition (Mattermost 5.25) and have the same issue.
```json
{
    "level": "error",
    "ts": 1596851939.9436836,
    "caller": "mlog/log.go:175",
    "msg": "Invalid or missing name parameter in request URL.",
    "path": "/api/v4/emoji/autocomplete",
    "request_id": "p6wdiqeb9ffpzdws8kcaaqzexr",
    "ip_addr": "*.*.*.*",
    "user_id": "************************",
    "method": "GET",
    "err_where": "Context",
    "http_code": 400,
    "err_details": ""
}
```

The same message does work when sending via a desktop or mobile web browser. It just doesn't work on the Andriod and iOS Mattermost app.

**Comment by lifepillar** [comment] 2022-01-19 08:18
Any update on this? I have this issue with Mattermost on iOS (but not on desktop): messages containing emojis don't go through.

App version: 1.48.2 (Build 382)
Server Version: 6.0.0
Database: mysql

**Comment by larkox** [comment] 2023-01-10 17:43
@lifepillar Are you still seeing this issue? Can you try on the latest beta version (V2)?

**Comment by lifepillar** [comment] 2023-01-13 19:43
@larkox I'm afraid I can't help, as I am not using Mattermost mobile any longer, sorry!

**Comment by larkox** [comment] 2023-01-13 21:04
Then I will close this issue. If anyone is still suffering from this, please reopen the issue.

**Closed by larkox** 2023-01-13 21:04 UTC
