### ISSUE TITLE
App crashes on launch 

### ISSUE THREAD

**Issue by dkudriavtsev** [mattermost/mattermost-mobile#2096] opened 2018-09-10 09:08 UTC
#### Summary
The app crashes on launch on Android. 

#### Environment Information

- Device Name: OnePlus 5T
- OS Version: Android 8.1.0, OxygenOS Open Beta 15
- Mattermost App Version: 1.11.0
- Mattermost Server Version: Not applicable, I don't even get to the server selection

#### Steps to reproduce

Launch the app

#### Expected behavior

App does anything but force close

#### Observed behavior

App crashes. Screenshot: http://imgur.com/a/kRbICqa

**Comment by amyblais** [comment] 2018-09-10 12:41
Hi @dkudriavtsev, thank you for reaching out.

Have you tried uninstalling and re-installing the app?

**Comment by dkudriavtsev** [comment] 2018-09-10 18:30
Yes. I have tried reinstalling and clearing data. The beta version also
crashes.

**Comment by amyblais** [comment] 2018-09-10 19:11
@dkudriavtsev 

When you launch the app, are you logged in or logged out?
Also, can you help press the "Send feedback" in case there are any error messages we can look at.

**Comment by dkudriavtsev** [comment] 2018-09-10 23:30
I have sent feedback from both the release and beta version of the app. I
am not able to see if I am logged in or out, the crash happens too quickly,
but I have never logged into the app (started crashing from.a clean install)

**Comment by amyblais** [comment] 2018-09-11 12:44
@enahum do you have access to the Android crash log for this?

**Comment by amyblais** [comment] 2018-09-11 17:52
@enahum Thank you, should I create a Jira ticket for this?

**Comment by dkudriavtsev** [comment] 2018-09-14 05:58
Maybe I should try starting the app with location mocking disabled...

**Comment by dkudriavtsev** [comment] 2018-09-14 06:00
Still crashes exactly the same way

**Comment by dkudriavtsev** [comment] 2018-09-14 06:03
[Video of the crash if it helps in any way](https://youtu.be/-h-bB6eTS6M)

**Comment by amyblais** [comment] 2018-09-14 12:37
I created a ticket here for our devs to look at a fix: https://mattermost.atlassian.net/browse/MM-12170.

As a temporary workaround, you can use the browser to access Mattermost on your phone.

**Comment by amyblais** [comment] 2018-09-14 12:48
Hi @dkudriavtsev, our devs came back to this and said that there is no way for us to reproduce the issue as we don't have this device model or OS version. The issue seems to be caused by one of our dependencies (https://github.com/GantMan/jail-monkey) and it would make sense to have the creators of that dependency to take a look at fixing this issue.

**Comment by jadielam** [comment] 2018-11-13 18:57
Any updates on this issue? I am having the same problem in my device. Google Nexus 4P with Android 8.1.0

**Comment by dkudriavtsev** [comment] 2018-11-13 22:00
What is Nexus 4P?
-- Dmitry Kudriavtsev

**Comment by amyblais** [comment] 2019-06-21 15:18
Closing via https://github.com/GantMan/jail-monkey/pull/36

**Closed by amyblais** 2019-06-21 15:18 UTC
