### ISSUE TITLE
mattermost crashed on android (pixel 8 pro android 14)

### ISSUE THREAD

**Issue by realpluut** [mattermost/mattermost-mobile#7927] opened 2024-05-01 13:57 UTC
#### Summary
Matter most starts, can type for about a minute, then app crashes without any info. 
in older versions of the app we did not have this issue 

### Environment Information
  - Pixel 8 Pro
  - Centos 8 (server) / android 14 (phone
  - Mattermost App Version: latest normal and beta from the play store
  - Mattermost Server Version: 9.5.1

#### Steps to reproduce
use an android 14 device 

#### Expected behavior
use it for 1 min, app keeps crashing just gone no warnings 

#### Observed behavior (that appears unintentional)
nothing, just typing and gone is the app 

#### Possible fixes
idk

**Comment by larkox** [comment] 2024-05-08 08:40
@realpluut Are you able to share the logs of the app? When you start the app, go to your profile -> Settings -> report a problem. That will get you the logs. You can send them my way at the mattermost community server (https://community.mattermost.com/core/messages/@daniel.espino-garcia).

Also, for the record, do you mind stating the exact version and build number? You can go to your profile -> Settings -> About Mattermost, and use the copy info button there to copy all the relevant information.

**Comment by larkox** [comment] 2024-05-22 13:08
Closing since we cannot reproduce and the original reporter doesn't answer.

If you have more information, please feel free to reopen.

**Closed by larkox** 2024-05-22 13:08 UTC
Labels: Bug Report/Open

**Comment by ro0tf1sh** [comment] 2024-07-02 19:59
I want to report please, because I have a major mattermost-app-crash issue and I may believe its the right place?

Mattermost Server 9.9.0, Build-Nummer: 9307585135, Debian 12
Nothing Phone 1, Nothing OS 2.5.6, Android 14
Oneplus 8, Android 14
Mattermost App Version 2.17.1 (tried clear cache already, also removed/installed the app, didnt help)

It was working years but since recently the app crashing, just so, also when sharing image/link the data is not being received (app crashing silently) and when trying again the phone informs me about the app has been crashed.

Can I send you the logs via mail or shall I upload here?

**Comment by larkox** [comment] 2024-07-03 08:45
@ro0tf1sh if the crash has only to do with sharing, there is a fix already slotted for the next release (2.18). Are you seeing such crashes anywhere else?

**Comment by ro0tf1sh** [comment] 2024-07-03 10:10
"Maybe" i may have experienced a crash longer time ago, but today - just asked my wife - we only may have problems when sharing something.
