### ISSUE TITLE
Login text field should trim the text input

### ISSUE THREAD

**Issue by 4shutosh** [mattermost/mattermost-mobile#6089] opened 2022-03-24 06:00 UTC
#### Summary
Login email/username field does not trims the text input and throws error if any whitespace is included.

### Environment Information
  - Device Name: Pixel
  - OS Version: Android 11
  - Mattermost App Version: 1.50.0

#### Steps to reproduce
1. Open the application
2. Enter Login email or username along with a space in the end
3. See the error

#### Expected behavior
White spaces from the ends should be removed

**Comment by amyblais** [comment] 2022-03-24 12:17
@enahum Let me know if I should open a bug ticket for this and whether this is a regression.

**Comment by enahum** [comment] 2022-03-24 12:21
@amyblais it is not a regression. Before opening any ticket, this should be discuss with UX in my opinion. Also idk if the server allows passwords or usernames to end with a space, if that is the case then this would be working as expected

**Comment by amyblais** [comment] 2022-03-24 12:46
I tested and it looks like server trims the whitespace. @matthewbirtch Let me know if you have thoughts on opening a ticket for this.

**Comment by matthewbirtch** [comment] 2022-03-24 20:09
I don't have any problem with trimming the whitespace, but the answer to the question from @enahum about whether passwords can end in spaces is important before deciding on this.

**Comment by matthewbirtch** [comment] 2022-03-24 20:13
I just tested this and passwords can have space characters at the end. I successfully created a password with 10 spaces at the end and it was accepted. So, I think this is working as it should based on the acceptable password rules.

I just tested changing a username to have spaces at the end and that did get trimmed when it saved by the looks of it. So I guess in theory we should be okay to do this with the email/username field, but not the password field

**Comment by tabarra** [comment] 2022-04-09 15:11
I don't think it's correct to edit the inputted password, BUT the username/email for sure is.  
Came here to actually make a a QoL feature request to trim the email as I lost about 5 stupid minutes today on it, but saw that this was already posted.

**Comment by amyblais** [comment] 2023-12-12 18:57
Closing some older issues. Please re-open this if the issue still reproduces on the latest version (v2.10),

**Closed by amyblais** 2023-12-12 18:57 UTC
