### ISSUE TITLE
Input box not honoring auto capitalization

### ISSUE THREAD

**Issue by licaon-kter** [mattermost/mattermost-mobile#1154] opened 2017-11-15 10:33 UTC
#### Environment Information

- Device Name: Xperia/Samsung 6.0.1
- Mattermost App Version: 1.4.0
- Mattermost Server Version: 4.3.1

#### Steps to reproduce
Have a keyboard that autosets letters as uppercase after a dot and at the start of the text (eg. Gboard )

#### Expected behavior
When giving focus to the input field or after a dot it should switch to uppercase or whatever the keyboard wants.

#### Observed behavior
Keyboard stays in lowercase mode all the time, ignoring the keyboard setting.

**Comment by lfbrock** [comment] 2017-12-11 20:02
@licaon-kter - sorry for the delay on this, reproduced the issue and filed a ticket here to fix: https://mattermost.atlassian.net/browse/RN-575

**Comment by stephenkiers** [comment] 2018-01-19 21:44
Is this issue reproducible with other auto-Capitalization keyboards, other than Gboard? I am unable to reproduce with Android Keyboard (AOSP), and it seems like this is a known issue with Gboard's keyboard, re: https://forums.oneplus.net/threads/auto-capitalisation-not-working-on-gboard.597573/

**Comment by stephenkiers** [comment] 2018-01-19 21:45
Tested on other keyboards and could not reproduce

**Comment by stephenkiers** [comment] 2018-01-19 21:46
Please re-open if reproducible with other keyboards.

**Comment by licaon-kter** [comment] 2018-01-20 08:54
Reproducible with:
* AnySoftKeyboard
* Multiling O Keyboard
* Sony Xperia Stock Keyboard

**Comment by stephenkiers** [comment] 2018-01-22 16:31
Ok, reopened for further testing.

**Comment by stephenkiers** [comment] 2018-01-22 19:38
Unable to reproduce on Gboard or AnySoftKeyboard. https://www.youtube.com/watch?v=i6BuDgRMPrc

Using App 1.6.0
Server 4.6.0 
on Emulated Nexus 5X

I am marking as cannot reproduce and I assume it has been fixed, or is an issue with individual device.

**Closed by stephenkiers** 2018-01-22 19:38 UTC

**Comment by licaon-kter** [comment] 2018-01-22 20:20
I can't test 1.6.0 as it's [not yet released](https://github.com/mattermost/mattermost-mobile/releases)

With 1.5.2, I can repro this on Sony 5.1.1, Sony 6.0.1 and Samsung 6.0.1.

**Comment by stephenkiers** [comment] 2018-01-22 23:39
yeah. I closed as 'already fixed' (perhaps unintentionally). If you still have issues after updating to 1.6, then we can re-open again, but I was not able to repro on the latest builds. :)

**Comment by stephenkiers** [comment] 2018-01-22 23:41
If you did want to try and reproduce on the current dev version, you may setup and try to reproduce on your machine. https://docs.mattermost.com/developer/mobile-developer-setup.html

**Comment by licaon-kter** [comment] 2018-02-08 11:59
Looks fixed in 1.6.0, thanks.

**Comment by stephenkiers** [comment] 2018-02-08 17:47
Thanks for following up
