### ISSUE TITLE
Android app crashes when reopening

### ISSUE THREAD

**Issue by yatzy** [mattermost/mattermost-mobile#1841] opened 2018-06-27 14:15 UTC
#### Summary
Android app crashes when reopening

#### Environment Information

- Device Name: Samsung Galaxy S8 
- OS Version: Android 8.0.0
- Mattermost App Version: 1.9.1 (Build 114)
- Mattermost Server Version: 4.10.0 (Build v4.10.0-1)

#### Steps to reproduce

Happened to me now couple of times this week. Basically when you open the app, change to couple of other apps and reopen the Mattermost, user interface throws an error.

#### Expected behavior

App returns to previously selected conversation.

#### Observed behavior

https://photos.app.goo.gl/HkMTXFWpUF3fb8Mc7 . 
Sorry I did not have time to take other than screenshot and not to copy the full error message.

#### Possible fixes

No idea. Hope this gets fixed :)

**Comment by amyblais** [comment] 2018-06-27 18:07
Hi @yatzy! Thank you for reaching out.

We are currently working on a v1.9.2 dot release which addresses this issue among other issues on v1.9 and v1.9.1 - I'll let you know when the dot release is out!

**Comment by yatzy** [comment] 2018-06-27 18:11
Thank you for the information. Cheers!

**Comment by amyblais** [comment] 2018-06-27 22:51
Hi @yatzy! v1.9.2 is now available.

**Comment by ashceryth** [comment] 2018-06-29 08:41
I had the same issue and can confirm that this has been resolved with the new release.

**Comment by amyblais** [comment] 2018-06-29 22:23
Sounds like the issue is fixed - however, @yatzy feel free to re-open this ticket if you still see the issue, and please open a new ticket if you see any other issues!

Thank you all!

**Closed by amyblais** 2018-06-29 22:23 UTC
