### ISSUE TITLE
Push notifications doesn't work

### ISSUE THREAD

**Issue by gintonic80** [mattermost/mattermost-mobile#7152] opened 2023-02-20 16:30 UTC
**Summary**

Push notifications doesn't work with Android or IOS apps.
There are no messages (absolutely) in the DEBUG log about any PUSH actions.

**Steps to reproduce**

Using docker-compose ymls. 
Mattermost Version: 7.8.0
Database Schema Version: 101
Database: postgres
Enable TPNS https://docs.mattermost.com/deploy/mobile-hpns.html
Enable Push in user profile settings.

**Comment by mb706** [comment] 2023-02-22 07:02
I am having a similar issue: new sessions created with the Android app version 2.1 do not get a "deviceid" and do not receive push notifications. I have users with version 2.0.1 for whom push notifications still work, but that could also be because their sessions were created with earlier versions of the app. I am therefore not yet sure if this issue exists only since 2.1.
I will have more time to investigate this on my end in the coming days, but wanted to report that gintonic80 is not the only one with this problem.

**Comment by mb706** [comment] 2023-02-24 20:48
Update on why this was not working for me: Apparently the way that device ids (Tokens) were retrieved has changed in some way recently (on Google's side), which some ad block firewalls were still blocking.

The React Native Notifications code that retrieves tokens is [here](https://github.com/wix/react-native-notifications/blob/e214fd96ecd86b704e9714b8a28335bd28cb1190/lib/android/app/src/main/java/com/wix/reactnativenotifications/fcm/FcmToken.java#L75-L87): when the Mattermost app is built in debug mode, then the problem is written out to the android log and can be seen with `logcat | grep ReactNativeNotifs`.

It would be useful if the app could give an indication about the fact that notifications are not working. Maybe by checking if there is no device id / token after a certain amount of time after calling Notifications.registerRemoteNotifications()? 

Sorry @gintonic80 , my issue is probably unrelated to yours.

**Comment by albearman** [comment] 2023-02-25 04:15
I have a similar problemI have a similar problem that the app (v 2.1, Android) is not registering for notifications and not getting the deviceToken. But this doesn't happen on all devices: some devices work fine on the same build. So far no dependency has been detected. As soon as we analyze devices with this problem - I'll come back with information.  that the app (version 2.1) does not register for notifications and does not receive a DeviceToken.

**Comment by mb706** [comment] 2023-02-27 10:41
I know almost nothing about react native, notifications, or the mattermost mobile code base, but maybe the following is helpful for someone who does:

If others still have problems, maybe it is related to [this change](https://github.com/mattermost/mattermost-mobile/commit/265b8b219306c3822f54f9702c00248d0ca306b6#diff-37dc05dc2ec940d3a0d862cf48dd19e46c5a8be1f08f2b54f8e6fe33bd7d3add). Before the change, `Notifications.registerRemoteNotifications()` was always called during startup (unless the app was not logged in), which runs the code that generates the token / deviceid for Android. Since this change, `registerRemoteNotifications()` only runs when `Notifications.isRegisteredForRemoteNotifications()` is false. However, as I understand it, `isRegisteredForRemoteNofications()` only checks whether notification permissions were granted, not whether a token is present. So maybe there are cases where notification permissions were granted but retrieving a token failed on the first try for some reason? Then, as I understand this, the app never tries to get a new tokenm unless the user logs out and logs back in again or something like this.

**Comment by spdrcd** [comment] 2023-03-03 21:57
> I have a similar problemI have a similar problem that the app (v 2.1, Android) is not registering for notifications and not getting the deviceToken. But this doesn't happen on all devices: some devices work fine on the same build. So far no dependency has been detected. As soon as we analyze devices with this problem - I'll come back with information.

I have went and downloaded an older version of the app v 2.0.x it seems like it has to do with android version rather than the app version? because my old phone which is on an older version of android has no problem receiving push notification

**Comment by bitdessert** [comment] 2023-03-07 05:43
Try deleting 'v2' from the device token settings. The token on the server and the token on the phone may have different values. I deleted v2 and checked that it works fine. The code after modification is 'storeDeviceToken(`${prefix}:${deviceToken}`);'

**Comment by gintonic80** [comment] 2023-03-07 08:12
> Try deleting 'v2' from the device token settings. The server and the phone may have different token values. I deleted v2 and checked that it works fine. The code after modification is 'storeDeviceToken(`${prefix}:${deviceToken}`);'

For example, my devices with v2 mobile app (Android) can't register deviceid and i have nothing to change. There is no problem with iOS v2 or Andriod v1.55.1 apps.

**Comment by spdrcd** [comment] 2023-03-07 16:16
Just went back to the google playstore, there seems to be a `mattermost - beta` version availible. push notification seems to be working on that one for my phone. I am on Android 12

**Comment by BobWs** [comment] 2023-04-01 09:07
I keep seeing this message on iOS devices, but I do get notifications and badges for new messages! The notifications are slow on arrival but it works.. How to get rid of the error message?

![D342791A-4107-4FE9-80BC-6A94114C4D6A](https://user-images.githubusercontent.com/5485820/229276901-b68d5088-3d2f-4eb3-940d-389397895e4e.jpeg)
![B721F7FF-612F-49B8-B7E9-0A2F1599739C](https://user-images.githubusercontent.com/5485820/229276906-d2f0b982-1ef7-456f-a1e4-024f3197625a.jpeg)

**Comment by spdrcd** [comment] 2023-04-01 13:21
I updated to the most recent version on android a few weeks ago, it seems to be working for me on Android now

**Comment by BobWs** [comment] 2023-04-05 14:07
> Are you receiving push notifications?

It is working now! I reinstalled the mobile apps on my iOS devices and logged in and now it is working, no more error message.👍

**Comment by spdrcd** [comment] 2023-04-05 14:47
> > Are you receiving push notifications?
> 
> It is working now! I reinstalled the mobile apps on my iOS devices and logged in and now it is working, no more error message.👍

Congratulations 💯

**Comment by larkox** [comment] 2023-07-31 15:50
This seems to be fixed, so I will close it. Feel free to comment if anyone is still seeing issues.

**Closed by larkox** 2023-07-31 15:50 UTC
Labels: Bug Report/Open

**Comment by MarcVJ** [comment] 2023-12-28 16:21
Hello,

We got stability problems with push notifications on mobile devices, using Mattermost Server Team Edition v9.3.0.
We have notifications in some cases so it doesn't seem to be the same issue. 

We were able to understand what follows :

Configuration :
- Phone is iPhone 8 with Mattermost Client v2.11.0, push notifications enabled for all messages, when online, away or offline. OS allows notifications, sound is on.
- Computer has Mattermost Client v5.6.0 app running.
- Another user sends me messages on a private conversation A (1 to 1).
 - We consider the push notification is working if it shows a message on the screen with a sound.

**Those tests are OK :**
If I am out of conversation A on computer and phone app is closed, I receive notifications on phone and computer.
If I display conversation A on any device, I don’t receive notifications on any device.

**This causes us trouble :**
If on the phone I use the upper-left arrow to get out of the conversation, I don’t receive notifications on phone or computer, even if I left the app in background, or if I lock the phone.
it seems to works as if I still was displaying the conversation.

![image](https://github.com/mattermost/mattermost-mobile/assets/38230768/7c3416d2-47ee-4aa3-9033-2db68f1a06f1)

Two ways we found to avoid this is to select another conversation on the mobile app, or to kill the app in the background. Doing this, we systematically had the notifications.

We will explain this to the users, but it is not very practical to do.

Would that be possible to fix this ?

Feel free to test if you have the same behavior.

Note that on one of our Android devices, there also is a back button on the system on bottom of screen, and if used, it behave differently, really gets out of conversation A and we have notifications. This is not possible on iPhone :
![d711122160161e07ab11f6ea30a3d3cd597818f2](https://github.com/mattermost/mattermost-mobile/assets/38230768/b224faf1-b9da-45b7-af5a-712d5285aacf)

Regards,
