### ISSUE TITLE
Scrolling issues on Android P DP2

### ISSUE THREAD

**Issue by PromoFaux** [mattermost/mattermost-mobile#1672] opened 2018-05-13 13:13 UTC
Apologies if there is an issue template, however it is not showing on the app I use for GitHub while mobile!

Since updating to the Android Phone DP2  beta, the scrolling in Mattermost 1.8 has been a bit iffy. Not seeing this issue in any other apps.

It seems to work fine if I hold and scroll, however if I try to "fling" scroll, it behaves weirdly. Almost as though it is going the opposite direction to the direction I want it. I will try and attach a video of said behaviours when I'm no longer mobile.

**Comment by PromoFaux** [comment] 2018-05-13 13:31
Example here : https://youtu.be/1wH7DhQf-cM

**Comment by amyblais** [comment] 2018-05-14 14:29
Thank you for reporting this @PromoFaux! 

I am not aware of an open ticket for this, so I'll help troubleshoot this.

A screenshot / video as a start will be helpful (as you mentioned).

**Comment by PromoFaux** [comment] 2018-05-14 17:46
Hi @amyblais Just shared a video with Elias over on your mm server. (Took it down from here because I realised it had identifying info of our server on it!)

Can share with you over there too, if you like?

**Comment by amyblais** [comment] 2018-05-16 17:44
@PromoFaux Did Elias provide feedback on the video and has there been any progress in troubleshooting the issue outside this Github ticket?

**Comment by PromoFaux** [comment] 2018-05-17 08:39
Last we left it, I was going to try and set up a dev environment and poke about to see if I could spot anything but real life has gotten rather in the way of that so far...

He reckons it's something to do with `react-native`

**Comment by amyblais** [comment] 2018-05-18 13:19
@PromoFaux Thanks for the update and no worries! Keep me updated on when you are ready to set up a dev environment or if you need any help with that.

**Comment by amyblais** [comment] 2018-06-01 15:10
Hi @PromoFaux, we haven't received an update so we'll assume that the problem is fixed or is no longer valid.

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.

**Comment by PromoFaux** [comment] 2018-06-10 21:01
Sorry Amy, been snowed under with "real life"! Issue still occurring, but I've not looked into why yet. Clearly nobody else has seen it happening! :)

**Comment by jfchevrette** [comment] 2018-06-14 14:47
I have the same issue on Android P DP3.

**Comment by raimaj** [comment] 2018-06-15 06:57
Same issue here on Android P Developer Preview 2.
Scrolling up a channel only works if done really slow. Normal scroll gesture makes the channel scroll up a bit and then bounce back down.

**Comment by PromoFaux** [comment] 2018-06-17 00:38
Is the v1.9 being released the same as the beta version 1.9 that was released on May 31st? If so, I switched to the beta version a while back to see if it had been fixed and still seeing the same issue :)

### Are you experiencing the issues with the Mattermost Mobile App, if so what version and OS?
App version 1.8 (and beta version 1.9) on an original Pixel XL running Android P DP3.

Not sure how to get logs/config files needed for this, any guidance would be appreciated!

**Comment by amyblais** [comment] 2018-06-18 15:16
v1.9 final is not the same as the beta version (it includes a lot more bug fixes and improvements) - the final version will be available in a few days. I'm asking my colleagues if they can repro / if 1.9 final includes fixes related to this (I don't have Android so not able to test myself).

**Comment by PromoFaux** [comment] 2018-06-18 18:59
Just as an update of some further experiments.

Mattermost Mobile v1.9 (build 110) downloaded from github release page - Same issue.
Switching servers between ours and pre-release.mattermost.com - Same issue.
Mattermost 1.9 on Android O - No issue.

It's likely the issue lies in Android P or React, but not sure which.

**Comment by amyblais** [comment] 2018-06-18 22:28
An engineer mentioned just now that there is probably not much we can do from our end for this problem as this seems to be an issue specifically on that platform on RN - perhaps would it help to start with checking with RN if this a known issue on their side or if they are working on a fix?

**Comment by PromoFaux** [comment] 2018-06-19 22:56
Yeah, I'll have a browse of RN repos see if there are any similar issues that have come up... in the mean time.. I've finally got around jumping into the rabbit hole...
![image](https://user-images.githubusercontent.com/1998970/41628429-67a49af2-741c-11e8-8c3e-bfbbc6558831.png)

**Comment by jfchevrette** [comment] 2018-07-13 17:07
This seem to be the same bug: https://github.com/facebook/react-native/issues/19434

I ran the reproducer using Expo on my device running DP4 and the scrolling behaviour is the same.

**Comment by PromoFaux** [comment] 2018-08-02 15:26
@amyblais Might be some movement on an alternative according to [this comment](https://github.com/facebook/react-native/issues/19434#issuecomment-408858552)

**Comment by APengue1** [comment] 2018-08-07 15:53
I have found a workaround to this issue until it can get fixed.

Phone: Pixel XL
Build: 9.0.0 (PPR1.180610.009, Aug 2018)
Mattermost Version: 1.10.0

With your scroll finger, scroll slightly and keep your finger in contact with the screen.
Take any other finger (best if on different hand) and keep it in contact with the screen.
You can now scroll normally with your scroll finger.
This allows you to scroll more quickly.

Without doing this, you're able to scroll, but only very slowly.

**Comment by H3npi** [comment] 2018-08-27 08:06
Got the same issue on a Pixel 2 XL

App Version: 1.11.0 (Build 133)
Server Version: 5.2.0 (Build 5.2.1)
Database: mysql
Android Version: 9
Build number: PPR1.180610.009

**Comment by micolous** [comment] 2018-09-08 08:37
@amyblais FYI, there's a "simple" workaround mentioned upstream: https://github.com/facebook/react-native/issues/19434#issuecomment-419245151

**Comment by amyblais** [comment] 2018-09-10 12:27
Hi all, letting you know that our developers are working on a fix / workaround for this, but it's still a work in progress and it will be part of a larger feature in a future release.

**Comment by philiplb** [comment] 2018-09-18 07:02
Glad there is already an issue about this. I experience the same on an Essential Phone with Android Phone, App Version 1.12.0.

**Comment by amyblais** [comment] 2018-10-01 16:37
Hi all, we've submitted a fix for this issue but we don't have Android P to test the fix internally. 

Would anyone here be able to help test the fix?  You'd need to sign up for [beta testing](https://play.google.com/apps/testing/com.mattermost.rnbeta) and then download the latest app version from Google Playstore.

PR: https://github.com/mattermost/mattermost-mobile/pull/2161
Jira ticket: https://mattermost.atlassian.net/browse/MM-12273

**Comment by philiplb** [comment] 2018-10-01 16:53
Hi, just tried it on my Essential Phone with P.
Scrolling works just fine now, bit when I got the pagination at the top, it doesn't load more. Just an endless loading indicator.

**Comment by cbenhagen** [comment] 2018-10-01 16:57
Loading and scrolling both work here. Thanks!

Philip <notifications@github.com> schrieb am Mo., 1. Okt. 2018, 18:53:

**Comment by compilenix** [comment] 2018-10-01 17:15
I can confirm that this works on the Google Pixel 2 XL with Android P (patch level September 5, 2018)

But i'm unable to load older messages, the loading never completes. This works using the current stable app version.

**Comment by amyblais** [comment] 2018-10-01 22:02
Hi @philiplb @compilenix For the "endless loading indicator" issue, are there any error messages you're seeing? We're not able to reproduce it internally so any additional information will be helpful.

**Comment by compilenix** [comment] 2018-10-01 22:52
No error, just the loading indicator. I noticed that this does not occur every time.
Sometimes i need to switch between chennels a couple of times and scroll up on each one. At some point no messages get loaded anymore, restarting the app solves the problem until it hangs again.

The first couple of messages, after switching to a channel, does get loaded every time. This problem occures only when older messages get loaded while scrolling.

**Comment by koxen** [comment] 2018-10-01 23:30
confirmed fix on xiaomi with android 9 👍

**Comment by amyblais** [comment] 2018-10-02 12:10
It looks like this issue is resolved so I'll close this Github ticket - @compilenix / @philiplb can I ask your help to open a new Github Issue and we can continue to troubleshoot the new issue on the loading indicator there?

**Closed by amyblais** 2018-10-02 12:10 UTC

**Comment by philiplb** [comment] 2018-10-02 12:32
@amyblais Sure!
