### ISSUE TITLE
Only 60 or less results shown when using searching.

### ISSUE THREAD

**Issue by eli-yip** [mattermost/mattermost-mobile#7725] opened 2023-12-18 04:49 UTC
#### Summary

When I try to use search feature on mobile app, I can only get about 60 result, while on desktop it can be about 200 or more.

### Environment Information
  - Device Name: iPhone 15 Pro
  - OS Version: iOS 17.2
  - Mattermost App Version: v2.11
  - Mattermost Server Version: v9.3.0

#### Steps to reproduce

Tap search button, and try to search message from someone or anything else that will have results more than 60, the mobile app will only show latest 60 results.

#### Expected behavior

Show all the results, or when I scroll down, it will refresh and get more results(like mattermost web app).

#### Observed behavior (that appears unintentional)

Only 60 max results.

#### Possible fixes

Your code lack of requesting for more data when scrolling to the end of page. Sorry I am not familiar about react native, but I can guess what is happening behind the bug.

**Comment by amyblais** [comment] 2024-01-09 17:00
Closing as a Help Wanted issue was opened for this.

**Closed by amyblais** 2024-01-09 17:00 UTC
Labels: Bug Report/Open

**Comment by cyberjam** [comment] 2024-01-14 04:15
@eli-yip Do you have a screenshot for reproduction? When I tried to reproduce it, I got 100 results.
<img width="347" alt="image" src="https://github.com/mattermost/mattermost-mobile/assets/20448972/fbaceebb-1880-45af-a51c-152781785737">

**Comment by cyberjam** [comment] 2024-01-19 12:43
Hi @eli-yip. yes, I'm using korean. This issue is not related to CJK or search engine.
The cause was that pagination had not been implemented.
[ref code](https://github.com/mattermost/mattermost-mobile/blob/1584208536d458f8753bc77494045ca98618adb1/app/screens/home/search/search.tsx#L189C13-L189C24)
Although it's a temporary solution, making the following changes will allow displaying up to 1000 results.
```js
searchPosts(serverUrl, newSearchTeamId, {...searchParams, per_page:1000}),
searchFiles(serverUrl, newSearchTeamId, {...searchParams, per_page:1000}),
```
I'm busy with another task, so implementing for this issue is challenging for me. 
I hope someone else pick up this issue.

Have a nice weekend!
