### ISSUE TITLE
Can't reconnect after session expire

### ISSUE THREAD

**Issue by tomaskavalek** [mattermost/mattermost-mobile#748] opened 2017-07-17 07:53 UTC
#### Summary
When login session expired, I am not able to reconnect to the server, despite of it's filled in the input.

#### Environment Information

- Device Name: iPhone 6S
- OS Version: 10.3.2
- Mattermost App Version: 1.0 (Build 34)
- Mattermost Server Version: 3.10.0

#### Steps to reproduce
Session expiration, then trying to connect to prefilled URL. Only flash display and keep on same screen. Even if I delete the URL, and fill again, I can't continue. I have to kill the app, then fill again, and continue.

#### Expected behavior
Connect to server and ask to fill credentials.

#### Observed behavior
Partialy described in Steps to reproduce.

#### Possible fixes
Don't know right now.

**Comment by lfbrock** [comment] 2017-07-17 15:39
Hi @tomaskavalek - can you try upgrading to [our new version on the app store](https://about.mattermost.com/mattermost-ios-app/) (Build 39) to see if the issue still reproduces?

**Comment by tomaskavalek** [comment] 2017-07-17 21:03
Thanks. I awaited newer dev version in TestFlight, but official release is newer. My bad. I'll try then report result.

**Comment by enahum** [comment] 2017-07-21 14:04
This looks like it was fixed, im going to close the issue but feel free to re-open if the issue persist

**Closed by enahum** 2017-07-21 14:04 UTC
