### ISSUE TITLE
User avatars & icons not loading

### ISSUE THREAD

**Issue by svenseeberg** [mattermost/mattermost-mobile#6081] opened 2022-03-22 15:42 UTC
#### Summary
User avatars are not loading in the mobile app. They work fine in the browser.

### Environment Information
  - Device Name: Dalvik/2.1.0 (Linux; U; Android 11; ONEPLUS A5010 Build/RQ3A.211001.001
  - OS Version: LineageOS 18.1
  - Mattermost App Version: 1.50.0
  - Mattermost Server Version: 6.5.0 (and some versions before)

#### Steps to reproduce
1. Set up Mattermost with Nginx reverse proxy and Gitlab authentication
2. Set avatars for some users.
3. Log in on mobile app with one user
4. Look into the users list and see that there are no icons

![image](https://user-images.githubusercontent.com/15197000/159519663-c66169b1-e3f8-4161-ade8-0935beab2dfe.png)

#### Expected behavior
User avatars should be there

#### Observed behavior (that appears unintentional)
API requests for user images (`/api/v4/users/USERID/image?_=1618945893144`) return a `401 Unauthorized`. Other API requests work without problems (return a 200 OK). That means chatting, channel/user listing, etc works as expected. Only avatars/icons are missing.

I used mitmproxy to dump the authorization headers. Using the bearer token with curl to access the same api ressource seems to work without issues:
```
curl -v -i -H 'Authorization: Bearer SECRET' "https://chat.example.com/api/v4/users/USERID/image?_=1636360275627"
```

I have no idea what makes the requests of the mobile app special. But for some reason the Mattermost server application decides to return a 401 for all users I tested.

**Comment by maxammann** [comment] 2022-04-13 12:23
I'm experiencing the same problem. The weird thing is that the bearer token itself seems to be valid.
Also only some users are affected.

**Comment by svenseeberg** [comment] 2022-04-13 14:35
It seems I made a mistake when interpreting the dump file. The BEARER token is not being sent with the request for the avatars. This issue could potentially be a duplicate of https://github.com/mattermost/mattermost-mobile/issues/4486

**Comment by amyblais** [comment] 2023-12-12 18:57
Closing some older issues. Please re-open this if the issue still reproduces on the latest version (v2.10),

**Closed by amyblais** 2023-12-12 18:57 UTC
