### ISSUE TITLE
Unable to go into the app: Unexpected error occurred

### ISSUE THREAD

**Issue by JounQin** [mattermost/mattermost-mobile#7677] opened 2023-11-21 14:16 UTC
#### Summary

As title

### Environment Information
  - Device Name: iPhone 15 Pro Max
  - OS Version: 17.1.1
  - Mattermost App Version: 2.10.0
  - Mattermost Server Version: N/A

#### Steps to reproduce

I can reproduce it consistently.

#### Expected behavior

No issue

#### Observed behavior (that appears unintentional)

![IMG_1610](https://github.com/mattermost/mattermost-mobile/assets/8336744/4fc275b2-d3da-44a0-a500-b20812169078)

#### Possible fixes

N/A

**Comment by amyblais** [comment] 2023-11-21 17:49
Hi @JounQin,  
1. What Mattermost server version are you on? You can find at Main Menu > About Mattermost.
2. Did this issue start to happen recently?
3. Are there any specific reproduction steps that lead to the crash?

**Comment by JounQin** [comment] 2023-11-21 23:39
1. 9.1.2
2. I just install the App the first time
3. No, install and open the App, crash

But it disappears today.

**Comment by amyblais** [comment] 2023-11-22 13:25
Thank you, opened https://mattermost.atlassian.net/browse/MM-55712.

**Comment by amyblais** [comment] 2023-12-04 23:26
The ticket was closed as we haven't been able to reproduce this internally. Let us know if the issue is still happening,

**Closed by amyblais** 2023-12-04 23:26 UTC
Labels: Bug Report/Open
