### ISSUE TITLE
Client on iOS 15.8 can’t add a 2nd server

### ISSUE THREAD

**Issue by davirond** [mattermost/mattermost-mobile#7771] opened 2024-01-21 10:14 UTC
I just installed the Mattermost app. I can déclaré a first sever without issue. I try to add a second one by either clicking on the + sign at the right of the sever name or on the icon on its left side. Both action generate a white part shortly showing at the bottom center of the screen and then disappears quickly. 

I would have expected a window to open allowing me to declare a new Mattermost server. 

device iPhone 7plus
iOS : 15.8
App version 2.12.0 (build 499)
Servers versions : 9.3.0 and 8.1.6

**Comment by mkaraki** [comment] 2024-01-21 13:41
Me too. In my case, I also couldn't open reaction list (Long press reactions) and message menu (Long press messages).

My Environment:
- Device: Xperia 5 IV (Japan docomo Edition)
- Android: 13
- App version: 2.12.0 (Build 6000499) and 2.12.0 (Build 6000501, Beta Edition)
- Server version: 9.3.0 (Team Edition), 9.4.1 (Enterprise Edition Free) and 9.5.0 (Enterprice Edition, Mattermost Community Server)

**Comment by peters77** [comment] 2024-01-21 19:54
Same here on, "+" Sign not working on start page, reaction bar missing in threads (can't edit a message or add emoji etc.).

device iPhone 13 mini
iOS : 17.2.1
App version 2.12.0 (build 499)
Servers versions : 9.3.0

**Comment by amyblais** [comment] 2024-01-22 16:04
Hi all, this sounds to be a duplicate of https://github.com/mattermost/mattermost-mobile/issues/7764. Would you be open to moving your comments there, and also reaching out to ``larkox`` (see his comment at https://github.com/mattermost/mattermost-mobile/issues/7764#issuecomment-1904252819) with more details?

**Comment by amyblais** [comment] 2024-01-22 17:10
Closing as a duplicate,

**Closed by amyblais** 2024-01-22 17:10 UTC
